### ISSUE TITLE
Error when upgrading cluster with terraform

### ISSUE THREAD

**Issue by nickvth** [rancher/terraform-provider-rancher2#1040]
Error when upgrading cluster 

Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=ServerError, message=Operation cannot be fulfilled on clusters.management.cattle.io "c-mhjrs": the object has been modified; please apply your changes to the latest version and try again, baseType=error]

resource "rancher2_cluster"

provider version 1.24.0

SURE-5634

**Comment by nickvth** [comment]
ignore this is fixed in 1.25.0

**Comment by nickvth** [comment]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 10s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 20s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 30s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 40s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 50s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 1m0s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 1m10s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 1m20s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 1m30s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 1m40s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 1m50s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 2m0s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 2m10s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 2m20s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 2m30s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 2m40s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 2m50s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 3m0s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 3m10s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 3m20s elapsed]
rancher2_cluster.cluster: Still modifying... [id=c-6cgcg, 3m30s elapsed]
╷
│ Error: [ERROR] waiting for cluster (c-6cgcg) to be updated: unexpected state 'error', wanted target 'active, provisioning, pending'. last error: %!s(<nil>)
│ 
│   with rancher2_cluster.cluster,
│   on cluster.tf line 2, in resource "rancher2_cluster" "cluster":
│    2: resource "rancher2_cluster" "cluster" {
│

**Comment by nickvth** [comment]
I thought it was fixed, but still occur

**Comment by Edge94** [comment]
Hello,

I have the same issue with Rancher v2.6.8 and rancher2 terraform provider 1.24.2 .
I have created a ticket at Suse support and I'm still waiting their feedback on the investigation.

If anyone has the same issue and additional information, it might be helpful to share here :-)

Thanks a lot

**Comment by a-blender** [comment]
@nickvth Hello, this is often due to an object conflict occurring in Rancher on the v3 management cluster object (that's what `clusters.management.cattle.io` is). Several controllers may be trying to modify the obj at the same time during the provisioning that Terraform kicks off, and this error indicates a race condition.

Are you still having this issue? Please try either running `terraform apply` a second time or retry the upgrade using the latest Terraform [v2.0.0](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v2.0.0).

@nickvth There has also been [a PR to add retry logic](https://github.com/rancher/terraform-provider-rancher2/pull/1033) to several Terraform resources. This enhancement is available starting in [v3.0.0](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v3.0.0) which is the release line for Rancher v2.7 clusters, so if you can successfully upgrade to a Rancher 2.7 cluster then I'd recommend to try using that TF version.

I will also be adding specific retry logic to the `rancher2_cluster` soon and I will test a cluster upgrade with that fix to ensure it is resolved.

**Comment by nickvth** [comment]
@a-blender we see this still on rancher 2.7.3 with tf rancher2 provider 3.0.0

**Comment by a-blender** [comment]
@nickvth On an upgrade to which Rancher version or did you run an infra/nodes update? Did running `terraform apply` a second time make the upgrade go through?

**Comment by nickvth** [comment]
@a-blender yes second apply will go through, so adding an retry as suggested will probably fix it.

**Comment by a-blender** [comment]
## Test Template

Terraform RC: v3.2.0

This server error is very difficult to reproduce and the team has concluded that adding retry logic to the `rancher2_cluster` Update function will fix the issue. To simulate the HTTP 500 error, I ran the [test plan](https://github.com/rancher/terraform-provider-rancher2/pull/1159#issue-1777810670) outlined in my PR where I enable cluster monitoring and run an update while the cluster is still provisioning. With my fix, Terraform should just retry the update instead of failing. If you are not able to simulate the server error but everything else works fine, I think that's fine and the issue can be closed.

**Comment by Josh-Diamond** [comment]
Ticket #1040 - Test Results - ✅ 
---

❗ Unable to reproduce this issue ❗ - attempted to reproduce with tfp-rancher2 `v1.25.0`, as well as, `v1.24.0`, on Rancher `v2.6.8`, following steps outlined [here](https://github.com/rancher/terraform-provider-rancher2/pull/1159#issue-1777810670)

---

Verified with TFP-Rancher2 `v3.2.0-rc2` on Rancher `v2.7.6`:
1. Fresh install of Rancher `v2.7.6`
2. Using TFP-Rancher2 `v3.2.0-rc2`, provision a downstream RKE1 cluster w/ 3 nodes, individual roles and k8s `v1.25`
3. Once cluster is up and `active`, scale up worker node pool to 3 nodes, and add an additional worker node pool w/ one worker node
4. After terraform successfully runs `terraform apply`, but while cluster is still scaling up via RancherUI, upgrade the cluster to k8s `v1.26`
5. Verified - cluster successfully scales up + upgrades k8s version, no 500 Error encountered; working as expected
