### ISSUE TITLE
Add support for rancher2 provider to support custom instance roles for node groups

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/terraform-provider-rancher2#1047]
w.r.t. the feature enhancement to add support for custom instance roles for EKS node groups - [https://github.com/rancher/rancher/issues/29071]

This ticket was created to track the progress to add support to allow rancher2 provider to accommodate this new feature.

`node_groups` configuration block for EKS will need to have a `nodeRole` field added to support this feature with rancher2 provider.

**Comment by Josh-Diamond** [comment]
Added label `status/release-blocker` because: 
- RancherUI requires `nodeRole cannot be nil for node_groups`
- TF plan  responds with `An argument named "nodeRole" is not expected here.`

Until `nodeRole` is added as an expected field to `node_groups`, provisioning EKS will not be possible

**Comment by a-blender** [comment]
## Testing template

#### Root cause
 
Add Terraform support for node group node role feature in EKS.

#### What was fixed, or what changes have occurred

The following things have been added
* Terraform rancher2 `eks_config_v2.node_role` field where you can specify the EKS node group node role ARN (it will not work with just the name that is selectable from the rancher ui)
* Terraform docs update for `node_role`
* Terraform docs update Kubernetes versions

#### Areas or cases that should be tested

Testing

- [x] 1 - EKS 1 node cluster via TF provider, no node role
- [x] 2 - EKS 1 node cluster via TF provider, custom node_role
- [x] 3 - EKS 3 node groups, 1 node each via TF provider, ng 1 and 3 no node role, ng 2 custom node role

<details><summary>main.tf</summary>
<p>

```
terraform {
  required_providers {
    rancher2 = {
      source  = "terraform.example.com/local/rancher2"
      version = "1.0.0"
    }
  }
}

provider "rancher2" {
  api_url   = var.rancher_api_url
  token_key = var.rancher_admin_bearer_token
  insecure  = true
}

resource "rancher2_cloud_credential" "foo" {
  name = "foo"
  amazonec2_credential_config {
    access_key = var.aws_access_key
    secret_key = var.aws_secret_key
  }
}

resource "rancher2_cluster" "foo" {
  name = var.eks_name
  description = "Terraform EKS cluster"
  eks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.foo.id
    region              = var.eks_region
    kubernetes_version  = var.eks_kube_version
    subnets             = var.eks_subnets
    security_groups     = var.eks_security_groups
    node_groups {
      name = "node_group1"
      instance_type = var.eks_instance_type
      desired_size  = var.eks_desired_size
      max_size      = var.eks_max_size
      min_size      = var.eks_min_size
    }
    node_groups {
      name = "node_group2"
      instance_type = var.eks_instance_type
      desired_size  = var.eks_desired_size
      max_size      = var.eks_max_size
      min_size      = var.eks_min_size
      node_role     = var.eks_node_role_custom
    }
    node_groups {
      name = "node_group3"
      instance_type = var.eks_instance_type
      desired_size  = var.eks_desired_size
      max_size      = var.eks_max_size
      min_size      = var.eks_min_size
    }
    private_access = true
    public_access  = true
  }
}
```

</p>
</details>

<details><summary>terraform.tfvars</summary>
<p>

```
# Rancher specific variables
rancher_api_url                          = <API URL>
rancher_admin_bearer_token               = <Rancher bearer token>

# AWS specific variables
aws_access_key                           = <access key>
aws_secret_key                           = <secret key>

# EKS specific variables
eks_name                                 = "ablender-eks-node-role-test"
eks_region                               = <region>
eks_kube_version                         = "1.24"
eks_subnets                              = <subnets>
eks_security_groups                      = <security groups>
eks_instance_type                        = "t3.medium"
eks_desired_size                         = 1
eks_max_size                             = 1
eks_min_size                             = 0
eks_node_role_custom                     = "arn:aws:iam::270074865685:role/ablender-2nodegroups-node-instanc-NodeInstanceRole-SBF895G87LLA"
```

</p>
</details>

Test 1 - PASS
Generated node role set

![image](https://user-images.githubusercontent.com/12955547/214586980-761fccd7-0ef5-41f0-ab5a-b84ddbf72fcc.png)

![image](https://user-images.githubusercontent.com/12955547/214587389-cc483e3f-24ac-4d76-95c2-8f64e07b4764.png)

Test 2 - PASS

![image](https://user-images.githubusercontent.com/12955547/214587435-830cf4e8-3077-4c27-b522-40e6af3bc02c.png)

Test 3 - PASS

#### What areas could experience regressions ?

Terraform rancher2, EKS prov
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by a-blender** [comment]
@Josh-Diamond This will be ready to test when Terraform 1.25.x is released for Rancher v2.7.x

**Comment by sowmyav27** [comment]
Moving it back to `Blocked` state. @annablender @Sahota1225 Please move it `to-test` when there is a TF binary tagged to test this fix out.

**Comment by a-blender** [comment]
@Josh-Diamond This is ready to test using Terraform rancher2 [v3.0.0-rc1](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v3.0.0-rc1). Please setup local testing on the rc version of the provider with this command

```
./setup-provider.sh rancher2 3.0.0-rc1
```

**Comment by Josh-Diamond** [comment]
Ticket #1047 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-70455b151e0d90cb9e6725a27008cf92a6b4eeac-head` with Terraform rancher2 `v3.0.0-rc1`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | EKS 1 node cluster via TF provider, no custom node role | ✅ |
| 2. | EKS 1 node cluster via TF provider, with custom node role | ✅ |
| 3. |  EKS 3 node groups, 2 without custom node role, 1 with custom node role | ✅ |

---

Scenario 1 - 
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream EKS cluster with 1 node group and w/o custom node role set (via terraform)
3. Verified - cluster successfully provisions, all pods/workloads active, YAML is accurate and as expected

---

Scenario 2 -
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream EKS cluster with 1 node group and using custom node role (via terraform)
3. Verified - cluster successfully provisions, all pods/workloads active, YAML is accurate and as expected

---

Scenario 3 -
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream EKS cluster w/ 3 node groups; 1 using a custom node role, and 2 without a custom node role
3. Verified - cluster successfully provisions, all pods/workloads active, YAML is accurate and as expected
