### ISSUE TITLE
[RFE] Add new resources for PodSecurityAdmissionConfigurationTemplate

### ISSUE THREAD

**Issue by a-blender** [rancher/terraform-provider-rancher2#1189]
### Is your feature request related to a problem? Please describe.

Rancher v2.7.2 now comes w/ a new CRD for [Pod Security Admission (PSA) Configuration Templates](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates) that can only be provisioned manually.

### Describe the solution you'd like

Add a new resource/datasource for [`rancher2_pod_security_admission_configuration_template`](https://github.com/rancher/rancher/blob/release/v2.7/pkg/client/generated/management/v3/zz_generated_pod_security_admission_configuration_template.go) so users can manage _custom_ admission configuration templates via Terraform for RKE and RKE2/K3s clusters. This is a continuation of the solution for PSACT support https://github.com/rancher/terraform-provider-rancher2/issues/1112.

### Additional context

SURE-6756

**Comment by snasovich** [comment]
This is not going to make it into TFP 4.0.0 release (TFP release corresponding to Rancher v2.8.0 release). For engineer to be assigned to it in the future, please consider work done in https://github.com/rancher/terraform-provider-rancher2/pull/1246 as a starting point.

**Comment by jiaqiluo** [comment]
PR was merged, now waiting for an RC.

**Comment by jiaqiluo** [comment]
Can be validated in https://github.com/rancher/terraform-provider-rancher2/tree/v4.1.0-rc1

**Comment by Josh-Diamond** [comment]
Ticket #1189 - Test Results - ✅ 
---

Verified with tfp-rancher2 `v4.1.0-rc1` on Rancher `v2.8-c4743333c5d37c32e91b6de5e2c6b1c23ac90fa8-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | create, update, and delete `rancher2_pod_security_admission_configuration_template` | ✅ |
| 2. | delete a `rancher2_pod_security_admission_configuration_template` resource when it is used by existing clusters | ✅ |
| 3. | create and delete a `rancher2_pod_security_admission_configuration_template` and an RKE2 or RKE1 cluster that uses it in the same TF configuration | ✅ |
| 4. | fetch an existing `rancher2_pod_security_admission_configuration_template` data source | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.8-head`
2. Using tfp-rancher2 `v4.1.0-rc1`, create a new custom `rancher2_pod_security_admission_configuration_template` resource
3. Verified - successfully created
4. Update the `rancher2_pod_security_admission_configuration_template` created in step 2
5. Verified - successfully updates
6. Delete the `rancher2_pod_security_admission_configuration_template` created in step 2
7. Verified - successfully deletes

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.8-head`
2. Using tfp-rancher2 `v4.1.0-rc1`, create a new custom `rancher2_pod_security_admission_configuration_template` resource
3. Verified - successfully created
4. Provision a downstream cluster using the custom `rancher2_pod_security_admission_configuration_template` resource created in step 2
5. Verified - cluster successfully provisions, utilizing custom PSACT
6. Delete the custom PSACT created in step 2, and currently in use by cluster created in step 4
7. Verified - DENIED: PSACT in use by cluster - (expected behavior)

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.8-head`
2. Using tfp-rancher2 `v4.1.0-rc1`, create a new custom `rancher2_pod_security_admission_configuration_template` resource and provision a downstream cluster using the custom PSACT
3. Verified - successfully created
4. Using tfp-rancher2 `v4.1.0-rc1`, delete the custom PSACT and downstream cluster created in step 2
5. Verified - all resources successfully deleted

---

Scenario 4 - ✅ 
1. Fresh install of Rancher `v2.8-head`
2. Via Rancher UI, create a custom PSACT
3. Using tfp-rancher2 `v4.1.0-rc1`, grab the existing custom PSACT and provision a downstream cluster with it
4. Verified - custom PSACT successfully grabbed via `data` source, and downstream cluster successfully provisions use the custom PSACT
5. Using tfp-rancher2 `v4.1.0`, terraform destroy the cluster created in step 3, and ensure the custom PSACT still exists.
6. Verified - custom PSACT is active and cluster is torn down
