### ISSUE TITLE
Remove keypair_name from machine_config_v2 documentation

### ISSUE THREAD

**Issue by dkeightley** [rancher/terraform-provider-rancher2#1192]
**Other details**
Underlying Infrastructure: AWS
Downstream clusters bootstrapped with Terraform

**Issue description**
The `keypair_name` argument appears to not be supported in the context of Rancher provisioning EC2. Comparing with previous issues ([1](https://github.com/rancher/rancher/issues/25765), [2](https://github.com/rancher/terraform-provider-rancher2/issues/948), [3](https://github.com/rancher/terraform-provider-rancher2/issues/148)) and [rancher/machine](https://github.com/rancher/machine/blob/master/drivers/amazonec2/amazonec2.go#L77C7-L77C7) this argument in the documentation for the terraform provider can add confusion.

**Expected behavior:**
Non implemented features should be removed from documentation

**Comment by a-blender** [comment]
A dev needs to validate that `keypair_name` field in TF is not supported in the Rancher backend for creating RKE2/K3s node driver clusters on EC2. If that's true, the PR can be reviewed and merged.

**Comment by thatmidwesterncoder** [comment]
I can confirm there are no mentions of this field on the backend of rancher, the only real place I can find it [is in an RKE1 test](https://github.com/thatmidwesterncoder/rancher/blob/93dbfff1a2d021df83407fe648c4c3be7fca7a7a/tests/framework/extensions/rke1/nodetemplates/aws_config.go#L19).

Can you go ahead and remove all references to this field in the code as well @dkeightley? That way we don't have any leftovers.

**Comment by a-blender** [comment]
@thatmidwesterncoder Thanks for looking into this! I'd ask that directly on the PR.

**Comment by dkeightley** [comment]
@thatmidwesterncoder sure, I've added a new commit to remove the references for EC2.

I notice we also do have keypair_name for OpenStack, which I expect is the same, shall I remove those references also?

**Comment by thatmidwesterncoder** [comment]
@dkeightley - sure, that sounds good to me as well. I'm not able to find any references to that as well other than for Harvester. But at the same time once again the only reference is for rke1 and it's in a test (not any app code).

**Comment by a-blender** [comment]
@thatmidwesterncoder We need to backport this PR to `release/v3` to release the fix for TF 2.7.7. The provider `release/v3` branch is for Rancher 2.7 and `master` is for Rancher 2.8 and the milestone here is targeted for 2.7.7.

Please do the following

1. Add a Test Template to this issue specifying which Terraform RC to test with/how to test (we removed a non-working field so this likely can just be closed)
2. Create a backport issue and backport the PR

Reach out to me if you need help :)

**Comment by thatmidwesterncoder** [comment]
## QA Test Template

### Root cause
Fields that existed in the terraform provider were not used by rancher, namely the keypair_name fields from the openstack and aws providers.

### What was fixed, or what changes have occurred
The fields were removed from the terraform provider. 
 
### Areas or cases that should be tested
**Terraform RC v4.0.0-rc2**. Just sanity checking to make sure the provider still works. Since the fields weren't working before it shouldn't effect anything.

### What areas could experience regressions?
N/A
  
### Are the repro steps accurate/minimal?
No repro steps necessary.

**Comment by thatmidwesterncoder** [comment]
@a-blender both are done. Let me know if I did the backport right - I followed the same process I used for rancher/rancher.

**Comment by klippo** [comment]
I've just tested this in our OpenStack cluster using 3.2.0-rc2 

This change breaks cluster creation, instances can no longer be spawned

```
  failureMessage: >-
    Failure detected from referenced resource rke-machine.cattle.io/v1,
    Kind=OpenstackMachine with name
    "cluster-b0678758-brgrl": Trying to access
    option  which does not exist

    THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR

    Type assertion did not go smoothly to string for key 

    [cmdCreateInner] error setting machine configuration from flags provided:
    Both KeyPairName and PrivateKeyFile must be specified
 ```
 
 Unless I'm missing something the change for OpenStack should be reverted 
 https://github.com/rancher/terraform-provider-rancher2/issues/1226

**Comment by thatmidwesterncoder** [comment]
Thanks for catching this @klippo! I've opened a couple PRs to revert the commit that effects openstack here: https://github.com/rancher/terraform-provider-rancher2/pull/1235 and https://github.com/rancher/terraform-provider-rancher2/pull/1236

**Comment by a-blender** [comment]
@thaneunsoo This doesn't need to be tested, the change was reverted so it can just be closed.

**Comment by thaneunsoo** [comment]
Closing based on @Andy-Blendermann's comment
