### ISSUE TITLE
Cluster Monitoring Resource Support

### ISSUE THREAD

**Issue by Oats87** [rancher/terraform-provider-rancher2#136]
The Terraform provider should allow the creation of:

Custom Alerts
Notifiers

at both the cluster and project scope. This should be in addition to allowing customization of the Cluster Monitoring configuration here: https://github.com/terraform-providers/terraform-provider-rancher2/issues/134

**Comment by rawmind0** [comment]
Merged PRs that solves this issue. Please, reopen it if needed.

**Comment by iridian-ks** [comment]
@rawmind0 I'm wondering why this was added as part of `rancher2_cluster` instead of a separate resource?

For example, at my org one team creates clusters and gives us admin on them. It would be nice to do

```
data "rancher2_cluster" "mycluster" {
    name = "mycluster"
}

resource "rancher2_monitoring" "mycluster" {
  cluster_id = data.rancher2_cluster.id
  // etc...
}
```

Since it's part of the `rancher2_cluster` resource my options are to configure monitoring manually or run Terraform and have it fail, manually import the cluster into Terraform and then finish running Terraform.

Logging, for example, is a separate resource, which is awesome.

EDIT:

Or I suppose this could work?

```
data "rancher2_cluster" "mycluster" {
    name = "mycluster"
}

resource "rancher2_cluster" "mycluster" {
  existing_cluster_id = data.rancher2_cluster.id
}
```

Seems weird though. The `rancher2_cluster` resource seems overloaded.
