### ISSUE TITLE
rancher2_node_templates not recognized after upgrade to 2.3.3

### ISSUE THREAD

**Issue by mc-meta** [rancher/terraform-provider-rancher2#195]
Hello,

we are currently using rancher2 provider version 1.7.0 and seems that after upgrading rancher from version 2.3.2 to 2.3.3 existing rancher2_node_templates in our rancher cluster are not recognized anymore and disappeared after a 'terraform refresh' from state file, while are still present as API objects.

'terraform apply' will create new node_templates afresh side by side old ones.

**Comment by rawmind0** [comment]
Hi @mc-meta , what is the kind of the affected node templates?? vsphere??

**Comment by mc-meta** [comment]
Hello @rawmind0 , problem seems to be present on vsphere and aws templates (that's all we have right now).

**Comment by rawmind0** [comment]
vsphere node template schema has been updated on Rancher v2.3.3 but not aws. Anyway it shouldn't happens this issue on none of the node templates.

Could you please explain a little bit the steps you follow?? I'd need to reproduce the issue

**Comment by mc-meta** [comment]
hello @rawmind0 

our terraform code is managing to:

1) deploy vsphere machines (vsphere provider)
2) form rke cluster from machines at 1) (rke provider)
3) deploy and bootstrap rancher on 2) (helm + kubernetes + rancher2 providers)
4) prepare needed resources on 3) to deploy new clusters on vsphere and aws (rancher2 provider)
5) create new clusters on vsphere and aws directly from (rancher2 provider)

to reproduce is probably enough to:

a) bootstrap a rancher cluster with v2.3.2
b) create node_templates for vsphere and aws and other needed resources
c) verify idempotency
d) create test aws and vsphere clusters using node_templates at point b)
e) update rancher to v2.3.3
f) verify idempotency again, is all goes as expected you'll experience that node_templates are not recognized anymore and terraform will plan to create new node_templates even if pristine objects are still there

Just for sake of completeness, we have upgraded rancher local cluster from v1.15.2-rancher1-1 to v1.15.3-rancher1-1 few days before upgrade to v2.3.3.

Let us know if you need us to perform any new tests in our lab setup

**Comment by rawmind0** [comment]
Hi @mc-meta , i was able to reproduce the issue.

Due to [this feature](https://github.com/rancher/rancher/pull/23718) included on Rancher v2.3.3, `rancher2_node_template` are now global scope objects with RBAC arounf them, instead of user scope objects as they were. This means that existing node templates are changing their `id` on upgrade, making that terraform provider will try to recreate them due to it's unable to find them by `id`.

As a workaround, if you are upgrading Rancher from previous releases to v2.3.3, you need to get node templates new id from Rancher API, refresh tfstate and import `rancher2_node_template` resources with new id.

```
$ curl -sk -X GET -H "Authorization: Bearer ${RANCHER_TOKEN_KEY}" ${RANCHER_URL}/v3/nodeTemplates | jq .data
$ terraform refresh
$ terraform import rancher2_node_template.<name> <new_id>
$ terraform apply
```

This mention is included on PR #197

**Comment by mc-meta** [comment]
Hello @rawmind0 ,

suggested remediation worker with 1.7.1. We may consider the issue as closed.

**Comment by rawmind0** [comment]
Thanks for the update @mc-meta
