### ISSUE TITLE
Unable to bootstrap cluster from scratch in a single successful Terraform run

### ISSUE THREAD

**Issue by iridian-ks** [rancher/terraform-provider-rancher2#214]
Hello, this is going to be a few issues wrapped in one. Let me know if I should break it up into multiple issues.

Issue 1: Monitoring config doesn't work on a new cluster

I'm not sure if I'm doing something wrong, but if I was to essentially copy the 3rd example in the Terraform docs here: https://www.terraform.io/docs/providers/rancher2/r/cluster.html

This code fails with this message:

```
Error: action [editMonitoring] not available on [&{c-vwpkd cluster map[clusterAlertGroups:https://rancher.rei.com/v3/clusters/c-vwpkd/clusteralertgroups clusterAlertRules:https://rancher.rei.com/v3/clusters/c-vwpkd/clusteralertrules clusterAlerts:https://rancher.rei.com/v3/clusters/c-vwpkd/clusteralerts clusterCatalogs:https://rancher.rei.com/v3/clusters/c-vwpkd/clustercatalogs clusterLoggings:https://rancher.rei.com/v3/clusters/c-vwpkd/clusterloggings clusterMonitorGraphs:https://rancher.rei.com/v3/clusters/c-vwpkd/clustermonitorgraphs clusterRegistrationTokens:https://rancher.rei.com/v3/clusters/c-vwpkd/clusterregistrationtokens clusterRoleTemplateBindings:https://rancher.rei.com/v3/clusters/c-vwpkd/clusterroletemplatebindings etcdBackups:https://rancher.rei.com/v3/clusters/c-vwpkd/etcdbackups namespaces:https://rancher.rei.com/v3/clusters/c-vwpkd/namespaces nodePools:https://rancher.rei.com/v3/clusters/c-vwpkd/nodepools nodes:https://rancher.rei.com/v3/clusters/c-vwpkd/nodes notifiers:https://rancher.rei.com/v3/clusters/c-vwpkd/notifiers persistentVolumes:https://rancher.rei.com/v3/clusters/c-vwpkd/persistentvolumes projects:https://rancher.rei.com/v3/clusters/c-vwpkd/projects remove:https://rancher.rei.com/v3/clusters/c-vwpkd self:https://rancher.rei.com/v3/clusters/c-vwpkd shell:wss://rancher.rei.com/v3/clusters/c-vwpkd?shell=true storageClasses:https://rancher.rei.com/v3/clusters/c-vwpkd/storageclasses subscribe:https://rancher.rei.com/v3/clusters/c-vwpkd/subscribe templates:https://rancher.rei.com/v3/clusters/c-vwpkd/templates tokens:https://rancher.rei.com/v3/clusters/c-vwpkd/tokens update:https://rancher.rei.com/v3/clusters/c-vwpkd] map[backupEtcd:https://rancher.rei.com/v3/clusters/c-vwpkd?action=backupEtcd exportYaml:https://rancher.rei.com/v3/clusters/c-vwpkd?action=exportYaml generateKubeconfig:https://rancher.rei.com/v3/clusters/c-vwpkd?action=generateKubeconfig importYaml:https://rancher.rei.com/v3/clusters/c-vwpkd?action=importYaml restoreFromEtcdBackup:https://rancher.rei.com/v3/clusters/c-vwpkd?action=restoreFromEtcdBackup rotateCertificates:https://rancher.rei.com/v3/clusters/c-vwpkd?action=rotateCertificates viewMonitoring:https://rancher.rei.com/v3/clusters/c-vwpkd?action=viewMonitoring]}]
```

What I did to work around this:

1. comment out the monitoring code
2. run Terraform which works
3. uncomment the monitoring code as-is
4. re-run Terraform, which successfully adds monitoring

I guess this makes sense, but really I think the monitoring should look more like logging. Meaning that monitoring/logging should be separate resources entirely.

Issue 2 - Can't wait on node pools

A funny issue is we can't create projects or handle RBAC when we create a new cluster because there aren't any nodes to form the cluster. We can create node pools, but Terraform doesn't wait for the node pools to be in the _ready_ state.

Ideally, if we can add a way for Terraform to poll the node pool for when they are ready. Maybe adding the attributes `wait` and `timeout` to control this?

EDIT: The error looks like this:

```
Error: [ERROR] Creating Project: Cluster ID c-vwpkd is not active

  on ../../../modules/rancher-setup/main.tf line 121, in resource "rancher2_project" "database":
 121: resource "rancher2_project" "database" {
```

To work around this you simply wait until the node pol is in the _ready_ state and then re-run the exact same Terraform code without modifications and the Projects are created.

Here's, ideally, what we can do with Rancher + Terraform:

```
resource "rancher2_cluster" "aws" {}

resource "rancher2_node_pool "aws_masters" {
  cluster_id = rancher2_cluster.aws.id
}

resource "rancher2_monitoring" "aws" {
  depends_on = [rancher2_node_pool.aws_masters]
}

resource "rancher2_logging" "aws" {
  depends_on = [rancher2_node_pool.aws_masters]
}

resource "rancher2_project" "database" {
  depends_on = [rancher2_node_pool.aws_masters]
}
```

So, this would create the new cluster in Rancher, which would provision AWS nodes and after that add on logging, monitoring and projects. This _should_ be doable by the provider. A source of inspiration could be the Helm provider, which does something similar with polling Kubernetes helm charts until they're ready/deployed.

**Comment by cloudnautique** [comment]
There is this resource:
https://github.com/terraform-providers/terraform-provider-rancher2/blob/3103513575036e41be3d1143ba192d9d9e22a903/website/docs/r/clusterSync.html.markdown

Which might address the issue you are describing since it waits for the cluster to become 'active'. At that point, you can perform actions on it. It seems the resource is missing from the docs page, but as far as I know it is available. We will need to get them added.

Let us know if this addresses the issue. The monitoring issue, might still be a problem we need to investigate.

**Comment by iridian-ks** [comment]
@cloudnautique nice, you're awesome. This is exactly what I was looking for. Sorry, I missed it.

I have a workaround for the monitoring issue, but hopefully we can look into it after the holidays. Thanks so much!

**Comment by rawmind0** [comment]
Please reopen issue if needed.

**Comment by iridian-ks** [comment]
@rawmind0 the 2nd issue is still not resolved. When I am creating a new Rancher cluster I have to comment out the monitoring config and then uncomment it after the cluster is up. This is kind of a *big* issue.

**Comment by rawmind0** [comment]
@iridian-ks , yeah working now on second issue with cluster monitoring, thanks for the advice.

**Comment by rawmind0** [comment]
It's weird. I've just used 3rd doc example and is working fine for me.

```
resource "rancher2_cluster" "foo-custom" {
  name = "foo-custom"
  description = "Foo rancher2 custom cluster"
  rke_config {
    network {
      plugin = "canal"
    }
  }
  enable_cluster_monitoring = true
  cluster_monitoring_input {
    answers = {
      "exporter-kubelets.https" = true
      "exporter-node.enabled" = true
      "exporter-node.ports.metrics.port" = 9796
      "exporter-node.resources.limits.cpu" = "200m"
      "exporter-node.resources.limits.memory" = "200Mi"
      "grafana.persistence.enabled" = false
      "grafana.persistence.size" = "10Gi"
      "grafana.persistence.storageClass" = "default"
      "operator.resources.limits.memory" = "500Mi"
      "prometheus.persistence.enabled" = "false"
      "prometheus.persistence.size" = "50Gi"
      "prometheus.persistence.storageClass" = "default"
      "prometheus.persistent.useReleaseName" = "true"
      "prometheus.resources.core.limits.cpu" = "1000m",
      "prometheus.resources.core.limits.memory" = "1500Mi"
      "prometheus.resources.core.requests.cpu" = "750m"
      "prometheus.resources.core.requests.memory" = "750Mi"
      "prometheus.retention" = "12h"
    }
  }
}
```

Cluster is created properly.  Are you doing something distinct?? I'd liked to reproduce the issue.

**Comment by iridian-ks** [comment]
Maybe it's because I'm using EC2?

```
resource "rancher2_cluster" "ec2" {
  name                      = var.name
  description               = "Created with Terraform by Middleware"
  desired_agent_image       = "rancher/rancher-agent:v2.2.8"
  desired_auth_image        = "rancher/kube-api-auth:v0.1.3"

  enable_cluster_monitoring = true
  cluster_monitoring_input {
    answers = {
      "exporter-kubelets.https" = true
      "exporter-node.enabled" = true
      "exporter-node.ports.metrics.port" = 9796
      "exporter-node.resources.limits.cpu" = "200m"
      "exporter-node.resources.limits.memory" = "200Mi"
      "grafana.persistence.enabled" = false
      "grafana.persistence.size" = "10Gi"
      "grafana.persistence.storageClass" = "default"
      "operator.resources.limits.memory" = "500Mi"
      "prometheus.persistence.enabled" = "false"
      "prometheus.persistence.size" = "50Gi"
      "prometheus.persistence.storageClass" = "default"
      "prometheus.persistent.useReleaseName" = "true"
      "prometheus.resources.core.limits.cpu" = "1000m",
      "prometheus.resources.core.limits.memory" = "1500Mi"
      "prometheus.resources.core.requests.cpu" = "750m"
      "prometheus.resources.core.requests.memory" = "750Mi"
      "prometheus.retention" = "12h"
    }
  }

  #
  # The configuration down here was computed by inspecting an EC2 cluster
  # created through the UI versus Terraform's defaults.
  #
  cluster_auth_endpoint {
    enabled = true
  }

  rke_config {
    authentication {
      strategy = "x509|webhook"
    }

    network {
      options = {
        flannel_backend_type = "vxlan"
      }
    }

    cloud_provider {
      name = "aws"
    }
  }

  lifecycle {
    ignore_changes = [
      annotations,
      labels,
    ]
  }

  depends_on = [null_resource.dependencies]
}
```

**Comment by gastoncan** [comment]
> @cloudnautique nice, you're awesome. This is exactly what I was looking for. Sorry, I missed it.
> 
> I have a workaround for the monitoring issue, but hopefully we can look into it after the holidays. Thanks so much!

Hi @iridian-ks ;
Can you please share with us how did you workaround the monitoring issue? I am experiencing the same problem as you.

Thanks in advance!

**Comment by iridian-ks** [comment]
@gastoncan which issue? If it’s the waiting issue then the production Terraform docs now have the cluster_sync resource available for you.

If it’s the metrics configuration then I’m still trying to work with Rancher on that. My workaround for that is to comment out all metrics configuration and then bring up the cluster and then uncomment and apply again. This works but, obviously, we don’t want to have to manually edit code in order to apply configuration.

**Comment by gastoncan** [comment]
> @gastoncan which issue? If it’s the waiting issue then the production Terraform docs now have the cluster_sync resource available for you.
> 
> If it’s the metrics configuration then I’m still trying to work with Rancher on that. My workaround for that is to comment out all metrics configuration and then bring up the cluster and then uncomment and apply again. This works but, obviously, we don’t want to have to manually edit code in order to apply configuration.

Thanks @iridian-ks for the response.
I meant to have a workaround for the monitoring issue.
Finnaly, I managed to configure the monitoring using the below code. I think it is not idemponent (because of the usage of "local-exec" provisioner without a "trigger"), but it's a good start.
I took the _curl_ commnad from the Rancher UI calls to the Rancher backend.
Do you have a better idea or a comment regarding my code?


```
resource "rancher2_cluster" "imported_cluster" {
  name = "my-cluster"
  enable_cluster_monitoring = true

######## grant the administrator user with cluster-admin role
  provisioner "local-exec" {
    command = <<EOT
      export USER=$(kubectl config view -o jsonpath='{.users[].name}')
      kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user $USER
    EOT
  }

########Initialize Rancher pods in the cluster
  provisioner "local-exec" {
    command = rancher2_cluster.imported_cluster.cluster_registration_token.0.command
  }
}

######## Wait for the cluster to be "active"
resource "rancher2_cluster_sync" "imported_cluster_sync" {
  cluster_id = rancher2_cluster.imported_cluster.id
}

########configure monitoring using remote API call as a workaround for the issue https://github.com/terraform-providers/terraform-provider-rancher2/issues/214
resource "null_resource" "configure_cluster_monitoring" {
  depends_on = [rancher2_cluster_sync.imported_cluster_sync]

  provisioner "local-exec" {
    command = <<EOT
      if [[ ${var.enable_cluster_monitoring} ]]; then
        curl "https://my-rancher/v3/clusters/${rancher2_cluster.imported_cluster.cluster_registration_token.0.cluster_id}?action=editMonitoring" \
          -H "cookie: R_SESS=${var.rancher_access_key}:${var.rancher_secret_key}" \
          --data "{ \
            \"answers\":{ \
              \"exporter-kubelets.https\": \"${var.exporter-kubelets_https}\", \
              \"exporter-node.enabled\": \"${var.exporter-node_enabled}\", \
              ........ # all the rest of the parameters to configure monitring
          } \
        }"
      fi
    EOT
  }
}
```

**Comment by pib** [comment]
I managed to work around the issue by giving the user creating the cluster "admin" permissions, but I believe it would actually work to just give them "editMonitoring" permissions on clusters in general. 

The issue seems to be that when a user creates a cluster, the role binding that is created to give them the "cluster creator" permissions takes a while to apply, and the rancher2 provider is not waiting for that before trying to apply the monitoring settings. I would consider that a bug in the provider and/or rancher.

The other thing that seems to be a bug is the fact that the cluster is being created in Rancher and then not saved in the state after the editMonitoring error occurs, leaving a "pending" cluster in Rancher that terraform doesn't know about.

**Comment by gastoncan** [comment]
> I managed to work around the issue by giving the user creating the cluster "admin" permissions, but I believe it would actually work to just give them "editMonitoring" permissions on clusters in general.
> 
> The issue seems to be that when a user creates a cluster, the role binding that is created to give them the "cluster creator" permissions takes a while to apply, and the rancher2 provider is not waiting for that before trying to apply the monitoring settings. I would consider that a bug in the provider and/or rancher.
> 
> The other thing that seems to be a bug is the fact that the cluster is being created in Rancher and then not saved in the state after the editMonitoring error occurs, leaving a "pending" cluster in Rancher that terraform doesn't know about.

Giving "Admin" for the user worked as a workaround; thanks for that.
How do I perform the above statement: 

> "give them "editMonitoring" permissions on clusters in general."?

**Comment by pib** [comment]
@gastoncan I think it needs to be done via the underlying Kubernetes cluster. I'm not sure exactly what would need to be changed or what changes would need to be made. Rancher uses a combination of RBAC and their own CRDs, so it usually takes a little digging around to figure these sorts of things out, which is why I just went with admin to begin with.

The part that is throwing me off currently is not knowing if "editMonitoring" can be used as a verb in RBAC or if it needs to be set up differently.

**Comment by pib** [comment]
Monitoring is enabled via the `enableClusterMonitoring` field on the `clusters.management.cattle.io` CRD that Rancher uses to manage clusters. So it seems that the "editMonitoring" API in the Rancher API doesn't directly map to RBAC under the covers. I'll probably resort to digging through the Rancher source to figure it out a bit later.

**Comment by pib** [comment]
@gastoncan so it turns out that Rancher currently just checks if the user has permission to "update" the cluster to determine if it can call the editMonitoring API: https://github.com/rancher/rancher/blob/master/pkg/api/customization/cluster/actionhandler.go#L68

So either the rancher2 provider should be waiting until the role template for cluster creators is applied before trying to edit the monitoring, or it should be setting the monitoring setting right off the bat (if that is a thing that can be done).

**Comment by gastoncan** [comment]
> @gastoncan so it turns out that Rancher currently just checks if the user has permission to "update" the cluster to determine if it can call the editMonitoring API: https://github.com/rancher/rancher/blob/master/pkg/api/customization/cluster/actionhandler.go#L68
> 
> So either the rancher2 provider should be waiting until the role template for cluster creators is applied before trying to edit the monitoring, or it should be setting the monitoring setting right off the bat (if that is a thing that can be done).

Thanks a lot for investigation @pib !
How can we address this fix? I am not familiar with bug fixes lifecycle in github. Should this actual issue to be reopen? Or we need a new one? @iridian-ks ? @rawmind0 ?

**Comment by pib** [comment]
I didn't spend too much time digging in to the rancher2 provider code, but it looked like it creates the cluster then edits the monitoring settings. I believe it should be able to set the monitoring config when it initially creates the cluster, which would eliminate this bug.

**Comment by rawmind0** [comment]
@pib, edit monitoring is done just if monitoring is enabled and you are providing monitoring answer with custom values.

**Comment by pib** [comment]
@rawmind0 ok, so I guess in that case the issue is that in that case it needs to wait for the role bindings for the cluster creator to be applied before attempting the monitoring change.

**Comment by rawmind0** [comment]
@pib not pretty sure about that. I can't reproduce the issue as commented [here](https://github.com/terraform-providers/terraform-provider-rancher2/issues/214#issuecomment-591608118),  

Due to sing admin user, deployment is working properly for me, i guess that may be it is a problem with user permissions.

**Comment by pib** [comment]
If it helps, I see the problem consistently with imported clusters, so perhaps it's something specific to those.

**Comment by rawmind0** [comment]
Good point @pib, thanks.. I'll investigate on this way.

**Comment by jbilliau5668** [comment]
I can confirm this issue exists with imported clusters; i can't get cluster-monitoring to work at all with an imported EKS cluster unless I run terraform apply again after the initial apply, and "add it in".

**Comment by pib** [comment]
This is still an issue I am seeing. The error actually prevents the cluster from being saved in the terraform state as well, so the next apply it fails because there's already a cluster with the same name. The only way to fix it is to do a `terraform import` and apply again OR to give the user more privileges temporarily while the apply is happening. Neither is a good solution :|

**Comment by pib** [comment]
In case anyone else finds this in the future, the temporary solution I am using is to ensure that the users which are creating the clusters also have the global "update" permission on cluster objects. In my case I edited the globalrole user resource and added "update" to the list of cluster permissions. This has to be done via kubernetes on the local cluster since the rancher ui won't let you edit global roles.
