### ISSUE TITLE
rancher2_certificate not having an import function

### ISSUE THREAD

**Issue by zraider7** [rancher/terraform-provider-rancher2#261]
We are trying to get our current k8s cluster in terraform and need to update some certs. Terraform won't touch our certs unless we import it and "rancher2_certificate" does not have an import option at this time (but I see rancher_certificate did). 
https://www.terraform.io/docs/providers/rancher2/r/certificate.html

Is there a timeline on when this feature will be available?
If not, do you have another way to do this that does not require deleting the cert and having terraform create it?

**Comment by rawmind0** [comment]
`rancher2_certificate` resource can't be imported from terraform due to certificate key value is not readable from rancher 2 API. 

To manage something on terraform, you need to create it from terraform or be able to import it. Unfortunately, just first option would be available for `rancher2_certificate` resource.

**Comment by zraider7** [comment]
Alright, that answers that then. Thanks for responding back!
