### ISSUE TITLE
Add LDAP User as a global admin after bootstrap and openldap configuration

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/terraform-provider-rancher2#272]
Currently you can only create a project or cluster binding which includes a user principal ID.  We are looking for a way to add a global admin which is a LDAP user using the rancher2_global_role_binding. It seems this resource does not allow you to provide a principal id.

The use case is bootstrap cluster, setup open ldap configuration, add user to role binding which doesn't exist yet as a user in the rancher instance yet. 

Maybe the issue is the rancher2_user doesn't allow a principal_id to be provided so I cannot create a LDAP user before trying to create the rancher2_global_role_binding.

**Comment by rawmind0** [comment]
@mitchellmaler, `rancher2_user` resource is just for managing rancher local users. LDAP users should be created from ldap itself.  BTM, `rancher2_global_role_binding` just accept user id due to they are special roles, they will be updated in next rancher releases. To add ldap user as global admin, you need to login first with ldap user (to get user id) and then can be added to global role binding. I know it's not ideal, but it's how it's working now. As mentinoned, it will be upgrade in next rancher releases.

**Comment by mitchellmaler** [comment]
@rawmind0 Ah okay I was afraid it was that way. Looking forward to relating a AD group to the Admin role in the next release! :D
