### ISSUE TITLE
RFE - Ability to add a Storage Class

### ISSUE THREAD

**Issue by dnoland1** [rancher/terraform-provider-rancher2#345]
Need to create a storageclass using rancher2 terraform provider. Equivalent of this in the UI:
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/468462/82393647-e8374a00-99fb-11ea-8b98-83a95aba259b.png">
which uses the API:
`POST /v3/cluster/<cluster id>/storageclasses`

**Comment by Mike-Ling** [comment]
I also need to add a class so that cluster monitoring can be enabled with persistent storage. Adding the class after the cluster has been provisioned does not work; the volumes remain in a pending state and the PV is never created.

The class needs to exist before the monitoring pods are deployed so I'm forced to deploy a cluster without monitoring and then enable monitoring in a second pass having first added the storage class.

**Comment by deniseschannon** [comment]
@dnoland1 Within the Rancher2 provider, we plan to implement features that are Rancher specific, any custom resources that can be created through kubectl, we do not plan to add into the terraform provider.
