### ISSUE TITLE
rancher2_cluster_alert_rule - add option to mute/deactivate alert rule

### ISSUE THREAD

**Issue by chrisreed87** [rancher/terraform-provider-rancher2#369]
Add an argument to deactivate or mute a cluster alarm from the Rancher2 provider, maybe tapping into this api function: https://github.com/rancher/rancher/blob/7c290b21ce68533aebc8ae18ec3cc4582d30779f/pkg/api/customization/alert/alert_action.go#L66

Would be helpful for either deactivating noisy alarms via automation, or creating an alarm that isn't ready to go "live"

gz#10625

**Comment by matttrach** [comment]
This feature request was made 4 years ago, but I believe it is no longer valid because it seems all alerts were removed in this PR https://github.com/rancher/terraform-provider-rancher2/commit/f7e2ae926ea47d8fe439c5e5e2bf03c1882759da. 
I am going to close this issue as stale, but feel free to open a new one if this is still a valid request in newer versions.
