### ISSUE TITLE
Can not create a new rancher2_cluster_template revision and update a cluster to use it in the same apply phase

### ISSUE THREAD

**Issue by gladavius** [rancher/terraform-provider-rancher2#375]
**Terraform Version**
Terraform v0.12.24

- provider.rancher2 Custom binary built from master

**Affected Resource(s)**
rancher2_cluster

**Terraform Configuration Files**
```
resource "rancher2_cluster" "this" { #
  depends_on = [rancher2_cluster_template.this]

  name                         = var.rancher_rke.name
  description                  = var.rancher_rke.description
  cluster_template_id          = rancher2_cluster_template.this.id
  cluster_template_revision_id = element(rancher2_cluster_template.this.template_revisions, var.template_revision_number - 1).id
}
```

We have a resource _rancher2_cluster_template_ that take a list of maps as an input to manage all our template revisions and then in the snippet above we use a variable (_template_revision_number_) to define which element of the list of revisions we want to use to create or update a cluster.

**Expected Behavior**
When adding a new revision definition in the list of maps, we expect terraform to create the cluster template revision and use it to update our cluster

**Actual Behavior**
When applying we have this error : 

```
2020-06-25T15:54:47.6357330Z Error: Provider produced inconsistent final plan
2020-06-25T15:54:47.6358249Z 
2020-06-25T15:54:47.6358786Z When expanding the plan for module.rancher-rke.rancher2_cluster.this to
2020-06-25T15:54:47.6359152Z include new values learned so far during apply, provider
2020-06-25T15:54:47.6359688Z "registry.terraform.io/-/rancher2" produced an invalid new value for
2020-06-25T15:54:47.6360056Z .cluster_template_revision_id: was null, but now
2020-06-25T15:54:47.6360549Z cty.StringVal("cattle-global-data:ctr-vkbnc").
2020-06-25T15:54:47.6360747Z 
2020-06-25T15:54:47.6361195Z This is a bug in the provider, which should be reported in the provider's own
2020-06-25T15:54:47.6361652Z issue tracker.
```

During the plan stage we can see this : 

```
2020-06-25T15:54:33.7894064Z # module.rancher-rke.rancher2_cluster.this will be updated in-place
2020-06-25T15:54:33.7896056Z resource "rancher2_cluster" "this" {
[...]
2020-06-25T15:54:33.7947781Z       cluster_template_id          = "cattle-global-data:ct-gkfhh"
2020-06-25T15:54:33.7955122Z       cluster_template_revision_id = "cattle-global-data:ctr-xtmhr" -> null
```

I expect terraform to understand that this value will be created during apply stage and we should have a "(known after apply)" instead of null for cluster_template_revision_id

**Comment by rawmind0** [comment]
I guess this is the expected tf behaviour, i don't think this is a provider issue.

`rancher2_cluster_template.this.template_revisions` is a nested list.  `element(rancher2_cluster_template.this.template_revisions, var.template_revision_number - 1)` doesn't exist at the plan stage. It will be created on apply (or not), then`cluster_template_revision_id` value is nil at this stage.  I guess that terraform is not showing you `Invalid index` error message due to the cluster already exist, instead if you test adding a new cluster using same `cluster_template_revision_id` , you should get something like that
```
# terraform apply
rancher2_cluster_template.test: Refreshing state... [id=cattle-global-data:ct-l8tn4]
rancher2_cluster.test: Refreshing state... [id=c-f94tw]

Error: Invalid index

  on cattle.tf line 376, in resource "rancher2_cluster" "test2":
 376:   cluster_template_revision_id = rancher2_cluster_template.test.template_revisions.2.id
    |----------------
    | rancher2_cluster_template.test.template_revisions is list of object with 2 elements

The given key does not identify an element in this collection value.
```

**Comment by gladavius** [comment]
@rawmind0 Thank you for your reply.

So basically what you say is that since template_revisions is a list it's impossible to add a new element (ie a new revision) and use it to update a cluster during the same execution?

Or did I missed something?

**Comment by rawmind0** [comment]
@gladavius , yes, it's what i understand from the terraform error log.

**Comment by caiconkhicon** [comment]
@rawmind0 : isn't it bad this way? Should we make revision a dedicated resource, and have something like `cluster_template_revision_attachment`?

**Comment by rawmind0** [comment]
@caiconkhicon , doing `cluster_template_revision` as dedicated resources is generating another issues. I was thinking about this option but doesn't seems better. 

For example, you couldn't create a `cluster_template` and `cluster_template_revision` (setting it as default) on the same execution, due to a cycle, `cluster_template`  needs to know `cluster_template_revision` ID to set it as default and `cluster_template_revision` needs to know `cluster_template` ID to be created.

```
resource "rancher2_cluster_template" "foo" {
  name = "foo"
  default_revision_id = rancher2_cluster_template_revision.foo.id
  description = "Terraform cluster template foo"
}

resource "rancher2_cluster_template_revision" "foo" {
  name = "V1"
  cluster_template_id = rancher2_cluster_template.foo.id
  cluster_config {
    rke_config {
      network {
        plugin = "canal"
      }
      services {
        etcd {
          creation = "6h"
          retention = "24h"
        }
      }
    }
  }
}
```

Anyway, with current implementation (once we patched it), you can create a new template revision as default and you could use it to update a cluster on same execution. What you can't do on terraform, is to use a `future` index on a list.

**Comment by caiconkhicon** [comment]
@rawmind0 : thanks for the explanation. I get it, it is a limitation of the current Rancher implementation. I mean, I am not a Rancher expert, but `rancher2_cluster_template` is really an empty item, since all configurations lay on `template_revisions`. IMO, having cluster template just block us performing many tasks (e.g. our current situation in this issue; change cluster template of a cluster).
Anw, thank you for your support. I appreciate it a lot.

**Comment by rawmind0** [comment]
@caiconkhicon , `rancher2_cluster_template` is not really an empty item. It's managing all `template_revisions` and defining the default one to be used, maintaining a version history. I don't think this is limiting many tasks, you can create and update template_revision_id on clusters if you set it as default on cluster_template.  What you can't do is to use a `future` index for updating existing clusters (it should work with new clusters)

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
