### ISSUE TITLE
Cannot install monitoring and Istio from private registry

### ISSUE THREAD

**Issue by cjbackman** [rancher/terraform-provider-rancher2#385]
Hi,

I'm trying to launch a cluster from Rancher in an air-gapped environment. I have specified a private registry for the cluster but for some reason the resources related to monitoring, ie everything in the namespaces cattle-prometheus and istio-system, are not pulled from the private registry as the rest. Instead it tries to pull those from docker hub.

Rancher - 2.4.5
K8s - v1.18.3-rancher2-2

Thanks, 
CJ

**Comment by rawmind0** [comment]
Hi @cjbackman, have you configured [Rancher default private registry](https://rancher.com/docs/rancher/v2.x/en/admin-settings/config-private-registry/) ?? It can be done using [rancher2_setting resource](https://www.terraform.io/docs/providers/rancher2/r/setting.html)

**Comment by cjbackman** [comment]
Hi @rawmind0 , no I have not set a global private registry, because I also have clusters with internet access where the private registry is not needed. However, I have set the private registry for the particular cluster (in the rancher2_cluster resource) which is air-gapped.

**Comment by rawmind0** [comment]
The private registry config you made in the cluster is fine. This registry would be used by RKE and k8s to download images. However, you should also update Rancher global private registry, if you want to install packages from catalog (helm) in an air-gapped environment (Rancher server without internet access). Could you please test again updating Rancher global private registry??

**Comment by cjbackman** [comment]
But if I set the global private registry, does that not mean all clusters will pull the system images from the private registry?

**Comment by rawmind0** [comment]
I'm guessing that your Rancher management server is running in an air-gapped environment, isn't it?? 

As you can read at [Rancher docs](https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/install-rancher/#c-render-the-rancher-helm-template), `systemDefaultRegistry = <YOURREGISTRY.YOURDOMAIN.COM:PORT>` should be provided for airgap installations. Also, `useBundledSystemChart = true` should be added if you didn't mirror our [system-charts](https://github.com/rancher/system-charts) repo

**Comment by cjbackman** [comment]
No, my Rancher management server is not running in an air-gapped environment. It is one of the clusters I want to launch using Rancher that is air-gapped. I have set useBundledSystemChart to true.

**Comment by rawmind0** [comment]
Ok, got it...Is this config working properly using Rancher UI instead the tf provider?? I think that the issue is related to this concrete config not the provider. 

Rancher server and all the clusters should have access to the system-library apps docker images. Rancher is using `systemDefaultRegistry` (docker-hub by default) to deploy system apps, like rancher-monitoring. As example, take a look to the [prometheus image definition](https://github.com/rancher/system-charts/blob/release-v2.4/charts/rancher-monitoring/v0.1.1/charts/prometheus/templates/prometheus.yaml#L26) included on rancher-monitoring chart

**Comment by cjbackman** [comment]
I have tested and I have the same issue with UI as I have with the Terraform provider. But is not strange that all other images, eg the rancher agent, is being pulled from the private registry? So far only the images related to monitoring ignore the private registry.

**Comment by cjbackman** [comment]
When specifying the private registry in the cluster configuration, should that not overwrite the systemDefaultRegistry?

**Comment by rawmind0** [comment]
> I have tested and I have the same issue with UI as I have with the Terraform provider. But is not strange that all other images, eg the rancher agent, is being pulled from the private registry? So far only the images related to monitoring ignore the private registry.

I was guessing that the same issue should happen from the UI due to the issue seems related to this concrete config not the provider. Rancher agent is in charge to get RKE config from rancher (including default k8s docker registry), and deploy the cluster. To deploy the RKE cluster, default k8s docker registry is used  to pull docker images and run them. Instead, rancher-monitoring (or any other app) is deployed from Rancher, that use `systemDefaultRegistry` to get images.  

> When specifying the private registry in the cluster configuration, should that not overwrite the systemDefaultRegistry?

Nope, `systemDefaultRegistry` is a Rancher global setting, configured on Rancher management server. It is common for all managed downstream clusters. Private registry in the cluster configuration is just for this concrete cluster. As mentioned, Rancher server and all the clusters should have access to the system-library apps docker images.

**Comment by cjbackman** [comment]
Does this mean it is not possible to have a mixture of downstream clusters that are air-gapped and some that are not?

**Comment by rawmind0** [comment]
It's possible the mixture but not with this config. As mentioned, Rancher server and all the downstream clusters should have access to the system-library apps docker images. Using a shared private docker registry as `systemDefaultRegistry` should address your issue.

Anyway, this issue is not related with the provider due to same result using the Rancher UI. Please, reopen it on [rancher repo](https://github.com/rancher/rancher) if needed.
