### ISSUE TITLE
rancher2_cluster disable cluster_auth_endpoint not working

### ISSUE THREAD

**Issue by Heiko-san** [rancher/terraform-provider-rancher2#402]
provider version: terraform-provider-rancher2_v1.9.0_x4
rancher version: v2.4.5

Enabling the endpoint (with or without fqdn/cert) works as expected.
Disabling seems to work (terraform applies a change) but then in the next run it wants to apply the change again.
Having a look in the web gui tells you auth endpoint is still active. Disabling it manually via web gui works.
```
cluster_auth_endpoint {                                                     
        enabled  = false
}
```
```
...
        windows_prefered_cluster                = false

      ~ cluster_auth_endpoint {
          ~ enabled = true -> false
        }

        cluster_monitoring_input {}
...

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.cluster.rancher2_cluster.cluster: Modifying... [id=c-lgwxj]
module.cluster.rancher2_cluster.cluster: Modifications complete after 1s [id=c-lgwxj]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by fmarceau-imagia** [comment]
+1 for this bug, same issue here as well !

**Comment by pburchard-equinix** [comment]
We have the same issue.

It's probably caused here: 
https://github.com/rancher/norman/blob/afd06f533ca3ffef490c6ce0ca7898271f39467f/clientbase/ops.go#L129

When update request is marshalled **enabled: false** value is omitted because it's configured this way here:

https://github.com/rancher/rancher/blob/f7516246e8f75178c8e2a4827eb0cd25a600dcd8/pkg/client/generated/management/v3/zz_generated_local_cluster_auth_endpoint.go#L12

**Comment by matttrach** [comment]
The last comment on this issue was 3 years ago, I suspect this issue was addressed when we upgraded the norman dependency in later versions. I am going to close this issue as stale, but feel free to open a new issue if this is still a problem in a supported version of Rancher and the Terraform Rancher2 provider.
