### ISSUE TITLE
Generating tokens for arbitrary users

### ISSUE THREAD

**Issue by MG2R** [rancher/terraform-provider-rancher2#428]
I'm trying to generate User Tokens for Users created with `rancher2_user`. I found the `rancher2_token` but it seems that can only manage the User Terraform is running as (admin). Is it in any way possible to generate tokens for arbitrary users? Is this something you're considering?

**Comment by rawmind0** [comment]
This feature is not available by the moment. Just own tokens can be generated by Rancher2 API. There is a open discussion to add this feature, https://github.com/rancher/terraform-provider-rancher2/issues/315#issuecomment-613142644.

This issue is duplicated. Please, follow this topic thread at https://github.com/rancher/terraform-provider-rancher2/issues/315
