### ISSUE TITLE
Disable src/dst checks

### ISSUE THREAD

**Issue by m4ce** [rancher/terraform-provider-rancher2#453]
The node_template resource supports an amazon ec2 config. It would be great if we could get the ability to disable source/dst checks on the nodes provisioned by Rancher. A typical use case would be the submariner gateways. They do require src/dst checks to be disabled. One is unable to automate the whole workflow without this option.

**Comment by rawmind0** [comment]
I think this feature is not supported on Rancher2, is it?? The feature should be added on Rancher2 before.

**Comment by m4ce** [comment]
@rawmind0 - let me create a request for it. Will link this issue.

**Comment by m4ce** [comment]
I temporarily hacked it using the node template userdata :/

**Comment by matttrach** [comment]
The last comment on this issue was 4 years ago, but I do want to apologize for the lack of response and support for your issue. It can be frustrating when you have an issue and you have tried several different options to resolve and end up having to accept some form of technical debt to accomplish your goals. That said I am going to close this issue as stale, but feel free to open a new issue for this if you still need help. This project, of course, can't supply any behavior that doesn't already exist in Rancher2, so if there is something that is lacking in that project please create an issue there first.
