### ISSUE TITLE
Cluster monitoring to its own resource

### ISSUE THREAD

**Issue by bentastic27** [rancher/terraform-provider-rancher2#455]
A user is running into an issue where they create a storage class via addon and enable monitoring (with persistence) via the cluster resource. The problem here is that monitoring is enabled before the user addons are created so the volumes for monitoring never get created.

Putting monitoring on its own resource (like logging is) should make this easier to work around.

**Comment by rawmind0** [comment]
> The problem here is that monitoring is enabled before the user addons are created so the volumes for monitoring never get created.

@bentastic27 , not fully understanding what do you mean with this. What `user addons` are you referencing, rke user addons??  If so,  are `rke user addons` really created after `rancher-monitoring` app?? Seem weird..

Could you please provide tf file to reproduce the issue?

**Comment by julienym** [comment]
Hi @rawmind0

I think what is happening is that the monitoring app is deployed before the addons. Therefore the StorageClass mentionned in the cluster monitoring configuration are inexistent at that deployment time. While the addons are created after, the monitoring app will still get created - but would have error at the beginning waiting for the absent SC.


Here is the relevent part of the templates mentionning the addons:
```
resource "rancher2_cluster_template" "this" {
  for_each = var.templates

  name        = "${var.subscription.company_code}${var.subscription.region_code}${each.key}${var.random_name}"
  description = var.rancher_rke.description
  members {
    access_type        = "owner"
    group_principal_id = "azuread_group://${var.rancher_rke.owners}"
  }

  "template_revisions" {
    content {
      cluster_config {
        rke_config {
          addons = lookup(template_revisions.value, "addons", "") != "" ? template_revisions.value.addons != "" ? join("---\n", [for file in template_revisions.value.addons : file("${path.module}/${file}") ]) : "" : ""
```
          
Here is the relevent part of the creation of the cluster:
```
resource "rancher2_cluster" "this" {
  cluster_monitoring_input {
    answers = {
      "grafana.persistence.enabled"               = true
      "grafana.persistence.size"                  = var.rancher_rke.monitoring.grafana.storage_size
      "grafana.persistence.storageClass"          = var.rancher_rke.monitoring.grafana.storage_class
      "prometheus.persistence.enabled"            = true
      "prometheus.persistence.size"               = var.rancher_rke.monitoring.prometheus.storage_size
      "prometheus.persistence.storageClass"       = var.rancher_rke.monitoring.prometheus.storage_class
      "prometheus.persistent.useReleaseName"      = true
    }

```

**Comment by rawmind0** [comment]
Hi @julienym , thanks for the info. 

It seems a race condition that rke cluster is eventually getting `active` status (up and running), before rke user addons deployment is finished. RKE is doing a fire and forget when deploy k8saddons and user addons, https://github.com/rancher/rke/blob/3d9bf164c371b1bcf6c534579e3115baad7de361/cluster/cluster.go#L885 , which could cause this scenario if monitoring requires any addons resource.

@bentastic27 , i don't think that the option to provide an own resource for cluster monitoring would address the issue, due to it seems a sync issue about when to configure and request monitoring deployment. If using own resource for cluster monitoring you'd have the same sync problem.

At the moment, a workaround would be to do a 2 passes tf apply:
1. Creates the cluster with addons included but with monitoring disabled.
2. Once cluster is deployed and `active`, update tf file, enabling and configuring cluster monitoring that requires any addons resource.

We are working on rke to provide a generic way to wait for rollout user addons to complete, that hopefully would address the issue. But by the moment, this is still in an early dev stage and no ETA for it.

**Comment by TomasManzano** [comment]
Hi. 

   Same problem here, but using the Longhorn app as persistence provider. The cluster monitoring is setup long before the longhorn app is deployed so the monitoring volumes get never created as the storage class doesn't exists at the time of the configuration of cluster monitoring.

A separate resource for cluster monitoring would enable me to fire it after longhorn is fully deployed and solve this problem. A two terraform apply strategy after modifying a tf file is not acceptable for automated deployments. There's more complicated solution available by using an external call to rancher API, but that's cumbersome. The perfect solution would be that cluster monitoring could be created as its own resource as logging currently is.

**Comment by matttrach** [comment]
The last comment on this issue was 3 years ago, but I do want to say something about multiple Terraform configs. There is a point in most Terraform configs where you need to break it down into multiple configs and orchestrate it, this is a normal growing pain when using Terraform to manage day 0, day 1, and day 2+ level systems. I have orchestrated with CI or Terraform itself in the past. I lean more towards Terraform orchestrating Terraform in my modules to reduce the number of dependencies. I have found orchestrating with CI to be very easy to manage and simple to understand. Personally, I would have a pre-user addon phase and a post-user addon phase to resolve this. 
That said, I am going to close this issue as stale, please feel free to open a new issue if this is still a problem and we can work together on solutions that work for you.
