### ISSUE TITLE
Node's hostname

### ISSUE THREAD

**Issue by m4ce** [rancher/terraform-provider-rancher2#459]
is it possible to default the node's custom name to the node's hostname? After deploying many nodes, they are all coming up with `ip-x.x.x.x` hostname rather than the required hostname.

If I look at the node's API, I see the followings:

```
"hostname": "foo1",
"labels": {
  "kubernetes.io/hostname": "foo1"
}
"name": "",
"nodeName": "ip-x-x-x-x.eu-central-1.compute.internal",
```

Would it be possible to default `name` to `hostname`?

**Comment by rawmind0** [comment]
Afaik no, it's using the node hostname. You could try adding [userdata]( https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_template#userdata) to update the node hostname when deployed.

**Comment by m4ce** [comment]
We already set the hostname in the ec2 userdata. If you see above, `hostname` is set correctly. It's just that the aws cloud provider seems to be reporting nodeName as the PTR of the internal VPC ip address..

**Comment by matttrach** [comment]
The last comment on this issue was 4 years ago, but I want to point out that cloudinit is not the most reliable resource to use for setting the hostname, especially on systems that use hostnamectl. I suggest using the run cmd cloudinit section to control hostnamectl to set the hostname properly rather than relying on the hostname section of cloudinit. In modules I support we using bash scripts to configure the OS due to this. I am going to close this issue as stale, but feel free to open another if you are still having trouble with this.
