### ISSUE TITLE
rancher2_user: Add argument to force password change upon first login

### ISSUE THREAD

**Issue by tibuntu** [rancher/terraform-provider-rancher2#465]
Title says it all. It would be awesome, if we could force our users to change their passwords upon first login.

This is an existing feature, if a user is created via the Rancher UI, but it doesn't exist for the rancher2_user resource.

Please let me know if I can provide more inputs for this idea.

**Comment by rawmind0** [comment]
The feature is there,but if this is added as configurable argument into the provider, it would generate a tf diff when the user has changed the password. The password is not readable from the Rancher API and couldn't be updated on tfstate

**Comment by tibuntu** [comment]
@rawmind0 that makes sense! Should I create an issue for the rancher/rancher repo to provide a value for the Rancher API like `changedInitialPassword: true` or even some hash? If I am not mistaken, you are a maintainer of the rancher/rancher repo, right?

**Comment by rawmind0** [comment]
@tibuntu , the problem is not on Rancher API. Rancher API already provides a user bool argument to force the user password change, [MustChangePassword](https://github.com/rancher/types/blob/release/v2.4/client/management/v3/zz_generated_user.go#L40). The problem is on terraform provider if `MustChangePassword` is a configurable argument. What'd happens if you set `MustChangePassword = true` and the user update the password (outside tf)?? It'd generate a diff on tf due to it's expecting `MustChangePassword = true` but it becomes false due to user has updated the password. Another beside issue, would be that the user password is not updated on tf, due to the user password can't be read from the Rancher API. Resuming, this would generate an inconsistency between user data at Rancher API and user data saved at tf state.

**Comment by caiconkhicon** [comment]
@rawmind0 : Can we make this parameter being "ignore_changes"? I mean, I expect the same behavior as the `password` field. Even though I set password in TF code, later when I change it on Rancher, TF won't ask me to change it back. Anyway, I want to force a new user to change his password once.

**Comment by rawmind0** [comment]
@caiconkhicon , with this scope, you could set `MustChangePassword` just once. `password` is not generating diff due to the password can't be get from the rancher API.

**Comment by maxaudron** [comment]
I'm also interested in using this when generating users for a customer. 

@rawmind0 Perhaps it would make sense splitting it to two options on the terraform side, MustChangePasswordOnce or something which is ignore_changes, and MustChangePassword which behaves normal.

Or maybe couple one of them to the password being set/changed if that is possible, would make most sense for usability.
