### ISSUE TITLE
Define private_registries as a list[]

### ISSUE THREAD

**Issue by oxr463** [rancher/terraform-provider-rancher2#486]
How can multiple private registries be defined? Is this a supported configuration?

```hcl
rke_config {
  private_registries [{
    url: foo
  }]
}
```

See also: https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_cluster_rke_config_private_registries.go

gz#12537

**Comment by rawmind0** [comment]
This is not a provider issue. Multiple registries can be added due to [`private_registries`](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#private_registries) argument is defined as a list. 

Please, take a look at [terraform docs](https://www.terraform.io/docs/configuration/attr-as-blocks.html#defining-a-fixed-object-collection-value) to know more about terraform list notation

```
# a constant list-of-objects expression
example {
  foo = "bar"
}
example {
  foo = "baz"
}
# Not recommended, but valid: a constant list-of-objects expression
example = [
  {
    foo = "bar"
  },
  {
    foo = "baz"
  },
]
```

**Comment by oxr463** [comment]
@rawmind0 thank you, closing this issue.

**Update:** the latter did not work, but the previous one did.
