### ISSUE TITLE
rancher2_cluster [monitoring]

### ISSUE THREAD

**Issue by ahmedfourti** [rancher/terraform-provider-rancher2#490]
Hello guys,

I faced an issue using monitoring config under resource "rancher2_cluster"

In the block rke_config we can provide a config for the monitoring which I did and set the provider to metric-server.
```
  rke_config {
    monitoring {
      provider = "metric-server"
    }
  }
```
However the replicas is always set to 0 by default even if the provider has been set, this will create a replicaset to 0...
Maybe it sould get a default value when provider is set ?

**Comment by rawmind0** [comment]
Hi @ahmedfourti , this issue is duplicated with #438 . 

Issue has been reproduced and a fix was already included at merged PR https://github.com/rancher/terraform-provider-rancher2/pull/468 and it will be available on next provider release. In the meanwhile, just adding [replicas](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#replicas) argument to the monitoring definition should workaround the issue

```
  rke_config {
    monitoring {
      provider = "metric-server"
      replicas = 1
    }
  }
```

Please, reopen issue if needed
