### ISSUE TITLE
cattle-private-registry - cluster - rke_config - not gettting removed

### ISSUE THREAD

**Issue by marino101** [rancher/terraform-provider-rancher2#511]
resource "rancher2_cluster" "cluster"
rke_config
    private_registries {
      url        = var...
      is_default = var...
      password   = ...
      user       = var...
    }

private registry for namespace cattle-system not getting removed
rancher provider latest
terraform 0.12.29

part plan output: 

- private_registries {
              - is_default = true -> null
              - url        = "index.docker.io" -> null
              - user       = (sensitive value)

**Comment by rawmind0** [comment]
what are the values of private_registries vars??

**Comment by marino101** [comment]
enabled  = true
  url      = "index.docker.io"
  user = dockerloginuser001plain
  password = data.google_kms_secret.xyz.plaintext

**Comment by rawmind0** [comment]
> part plan output:
>
> private_registries {
> - is_default = true -> null
> - url = "index.docker.io" -> null
> - user = (sensitive value)

If tf plan outs this diff, doesn't seem var values are these, the var values seems to be nil. `private_registries` should work fine and be idempotent, have you tested setting fixed values on privetr_regitries instead vars??

**Comment by marino101** [comment]
hi rawmind, thank you for your time, i hope i am not confusing you to much or myself for that matter. Setting the resource goes fine the issue we noticed is that the cattle registry is not getting removed from rancher when you remove the registry part from the rke_config. at least that was our experience.

**Comment by rawmind0** [comment]
Hi @marino101 , the first issue explanation was not so detailed. If your issue is removing private_registries (empty), this is a know issue, due to [PrivateRegistries at RancherKubernetesEngineConfig go struct](https://github.com/rancher/types/blob/release/v2.4/client/management/v3/zz_generated_rancher_kubernetes_engine_config.go#L48) is defined as `[]PrivateRegistry` with the json tags `json:"privateRegistries,omitempty"` on Rancher API. `privateRegistries = []PrivateRegistry{}` is treated as empty value and it's omitted on API request when json is marshalled. 

We are working to address this kind of issues.

**Comment by marino101** [comment]
Ok thank you for the update and for your patience. have a nice day.
