### ISSUE TITLE
Allow async update of k8s clusters

### ISSUE THREAD

**Issue by MG2R** [rancher/terraform-provider-rancher2#519]
Currently, when you upgrade a k8s cluster by changing the version in `rke_config`, Terraform waits for the upgrade to complete before returning. Would it be possible to have setting which allows Terraform to just issue the upgrade and move on? Waiting for the upgrade doesn't scale well. My test cluster with a mere 9 nodes already takes more than 10 minutes to complete.

In the UI I can "set and forget". I looked through the argument list for `rancher2_cluster`, but I don't see an option to do the same with Terraform. Is this a bad practice?

**Comment by rawmind0** [comment]
The provider not always wait until cluster is `active`, depends on the kind of cluster. On update, this providers waits until cluster reach same state it was, https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_cluster.go#L324 Have you consider to extend the cluster tf timeout??

With your proposal, how to check if the upgrade has been run successfully or not?? How to manage cluster dependencies, like namespaces, projects, etc??

**Comment by MG2R** [comment]
> With your proposal, how to check if the upgrade has been run successfully or not??

Whether or not the upgrade is successful, is nothing Terraform can change, react to or deal with, so in my mind it makes no sense to wait for this condition. Again, how do you scale this? If I allow a single node to be offline at a time, updating a 9-node cluster takes about 12 minutes. What if I have a hundred nodes? I can't have Terraform wait for this.

I'm guessing the root difference between our understandings is the same as in #520. I'm looking at this from the perspective that I want Terraform to set a desired cluster state up in Rancher and then Rancher is responsible for getting the cluster to that desired state. Terraform's job for a cluster upgrade is to increase the desired kubernetes version of a cluster in Rancher. If it was able to do that, the Terraform run did its job and in my eyes shouldn't wait around for Rancher to actually perform the upgrade.

As in #520: it's quite possible the Rancher API does not provide this way of working. If that's the case I'm sorry I created an issue here.

**Comment by rawmind0** [comment]
> Whether or not the upgrade is successful, is nothing Terraform can change, react to or deal with, so in my mind it makes no sense to wait for this condition. Again, how do you scale this? If I allow a single node to be offline at a time, updating a 9-node cluster takes about 12 minutes. What if I have a hundred nodes? I can't have Terraform wait for this.

Terraform should react if a config can't be applied, because one of the tasks that terraform should do is check the desired and real states and reconcile them if needed. Terraform is executing tasks in parallel if possible (assuring dependencies). Not fully understanding your point. To add nodes to a custom cluster, you don't need to update cluster from tf provider, just boot your nodes and execute the cluster_registration_token command with proper roles. This can be done in parallel, expecting similar wait duration with 1 or 100 nodes, if cluster_registration_token command is being executed in parallel in every node.

> I'm guessing the root difference between our understandings is the same as in #520. I'm looking at this from the perspective that I want Terraform to set a desired cluster state up in Rancher and then Rancher is responsible for getting the cluster to that desired state. Terraform's job for a cluster upgrade is to increase the desired kubernetes version of a cluster in Rancher. If it was able to do that, the Terraform run did its job and in my eyes shouldn't wait around for Rancher to actually perform the upgrade.

How or when would you noticed that you config is not working/applied fine?? On next terraform apply?? I mean, if you set your desired state on a tf file, but you are not checking assuring that the desired state is actually achieved, what's the point of terraform tfstate??

**Comment by MG2R** [comment]
> Terraform is executing tasks in parallel if possible (assuring dependencies). Not fully understanding your point. 

But two Terraform runs can't happen at the same time. Say my cluster update from 1.18 to 1.19 takes an hour because it's a big cluster. That means during that hour no other changes can be made with Terraform, even if it would be possible with kubectl/rancher ui, because the Terraform run is waiting for the entire cluster to be updated. 

Example:

* Team member A starts the update from 1.18 to 1.19. This update takes an hour.
* 20 minutes in, Team member B wants to add a namespace. He can't because Terraform is still waiting for the update to complete, so a new run cannot be started. 

Adding namespaces is possible during cluster updates in Rancher (because the kubernetes cluster never is unavailable). That's what I mean with I'd like to be able to start the update with Terraform, but not wait for it to complete. Waiting is fine with small clusters, but it becomes problematic at scale.

**Comment by MG2R** [comment]
>  if you set your desired state on a tf file, but you are not checking assuring that the desired state is actually achieved, what's the point of terraform tfstate??

Once the update has started, the desired state is already achieved, as the `rancher2_cluster` resource will already see the cluster as set to the correct version. The underlying nodes are not all running as the new version, but Rancher is taking care of it in the background. The API already reports the new version.

Try this: set up a cluster for version 1.18 with Terraform, then start updating it to 1.19 in the Rancher UI. During the update, set the version to 1.19 in your Terraform config and make a plan. Terraform will say nothing needs to be done.  On Terraform's end, as soon as Rancher is set to roll out the correct Kubernetes version, there is nothing left to be done.

**Comment by rawmind0** [comment]
> Example:
>
> * Team member A starts the update from 1.18 to 1.19. This update takes an hour.
> * 20 minutes in, Team member B wants to add a namespace. He can't because Terraform is still waiting for the update to complete, so a new run cannot be started.

For sure you have to wait. What happens if the update fails?? When or how do you noticed it?? 
Anyway, simple option here would be split tf files and states to decouple resources and tf execution, one with the "infra" and the cluster definition and another one for functional resources like namespaces, projects, apps,....

> Once the update has started, the desired state is already achieved, as the rancher2_cluster resource will already see the cluster as set to the correct version. The underlying nodes are not all running as the new version, but Rancher is taking care of it in the background. The API already reports the new version.

This is how terraform works. You define a desired state and terraform is in charge to achieve it, comparing current resource states with state saved at tfstate. If actions are not updating tfstate, then makes no sense to have it. Beside the config is set on the Rancher resource, tf is forcing desired state is applied. 

> Try this: set up a cluster for version 1.18 with Terraform, then start updating it to 1.19 in the Rancher UI. During the update, set the version to 1.19 in your Terraform config and make a plan. Terraform will say nothing needs to be done. On Terraform's end, as soon as Rancher is set to roll out the correct Kubernetes version, there is nothing left to be done.

Normal, because the Rancher cluster info and the tfstate resource info are the same. Terraform is just taking care of the state when terraform itself is doing the change, just to assure it's applied.

Try this: set up a cluster for version 1.18 with Terraform, then start updating it to 1.19 in the Rancher UI. During or when the update is already finished, running terraform plan again without tf file update, Terraform will do a plan to undo the UI update.

**Comment by MG2R** [comment]
> Anyway, simple option here would be split tf files and states to decouple resources and tf execution, one with the "infra" and the cluster definition and another one for functional resources like namespaces, projects, apps,....

Interesting. I hadn't considered this. I split my state files between logical groups of infra but indeed, an extra split here might make sense. Thank you for your time and elaborate answers. It's clear there's no code change to the provider necessary for this. I'll be able to work on this further now. Thank you again!
