### ISSUE TITLE
Support creation of basic-auth secret 

### ISSUE THREAD

**Issue by raelix** [rancher/terraform-provider-rancher2#555]
Hi everyone,

I’m using rancher2_catalog_v2 to add artifactory helm repo to the new rancher 2.5.3. The problem I’m facing is related to the authentication with artifactory, the rancher2_catalog_v2 needs a secret name and namespace but the supported type seems to be just basic-auth.
I’m not able to create a secret of basic-auth type with rancher provider rancher2_secret.
Are there any suggestions or work-around? Is this something you will support?

Thanks in advance

gz#14434

**Comment by raelix** [comment]
After some investigation, seems that the new rancher2_catalog_v2 allows catalog login passing credentials thought a secret (type basic-auth) but this type of secret can't be created with rancher provider, this sound as a big limitation because requires the use of another provider

**Comment by raelix** [comment]
Hello, are there any updates on this?

Thanks in advance

**Comment by ztj** [comment]
While awaiting an enhancement for this to be possible directly, I did come up with a bit of a hacky (but easy to swap out for the real thing later) workaround you might find useful.

I created a helm chart that makes it easy to create the correct type of secret with really nothing else to it. I published this in a public helm repo, just a very simple one published on GitHub Pages. I add a public rancher2_catalog_v2 for that public repo, I create a rancher2_app_v2 for this super simple secret creating chart, and voila, I have the correct secret. 

From there I create the real, protected rancher2_catalog_v2 referencing the secret from the previous hacky workaround. This works out okay because the actual secret values are ultimately created/fed through secure channels, albeit with (relatively) a lot of unnecessary duplication and overhead.

When the rancher2_secret is able to produce the correct type of secret, it will be easy enough to swap out the workaround catalog and app and swap in a rancher2_secret in its place. The now unnecessary app and catalog should be deleted and cleaned up in the process as well.

I found this workaround to be more appealing than trying to link together multiple Terraform module "apply" runs as in my case this is happening in the same module that creates the cluster and the kubernetes provider can't be used in the same apply run as the thing that provides the k8s credentials.

If you have a similar situation you could alternatively consider using something like terragrunt to run a few modules in sequence passing outputs from one as inputs to the next, etc. Terragrunt seems to be a generally useful tool for compensating for Terraform's weaknesses even when they stem from specific provider behaviors. It's worth checking out.

**Comment by raelix** [comment]
Hi @ztj thanks for the suggestion but unfortunately this is not applicable for air-gapped scenario where the helm repo needs the authentication and sincerely add terragrunt or something similar could create a lot of complexity which requires then more maintenance. 
The good approach here should be allow in the rancher provider to pass user and password until the provider itself doesn't support the creation of the required secret.

**Comment by rawmind0** [comment]
Hi all, thanks for reporting this issue. You are right, we are already working to add rancher2_secrets_v2 resource to be able to generate distinct secrets types at Rancher explorer.

**Comment by raelix** [comment]
Hello @rawmind0  thanks for the update, do you know already what will be the target release?

Thanks in advance

**Comment by rawmind0** [comment]
Fix included at new Rancher2 tfp release v1.13.0
