### ISSUE TITLE
Creating an app using rancher2_cluster as a datasource is not idempotent

### ISSUE THREAD

**Issue by ba-work** [rancher/terraform-provider-rancher2#594]
I don't think I'm doing anything unintended:
1. query for cluster id
2. create project based on cluster id
3. create namespace based on project id
4. create app based on namespace and project ids

The query on step 1 always marks `id` as `(known after apply)` which for some reason causes everything else to be: `must be replaced` (except for the namespace?)
```tf
data "rancher2_cluster" "demo_cluster" { name = "demo-cluster" } # this
resource "rancher2_project" "demo_project" {
  name       = "demo-project"
  cluster_id = data.rancher2_cluster.demo_cluster.id
}
resource "rancher2_namespace" "demo_namespace" {
  name       = "demo-ns"
  project_id = rancher2_project.demo_project.id
}
resource "rancher2_app" "demo_namespace" {
  name             = "demo-app"
  project_id       = rancher2_project.demo_project.id
  target_namespace = rancher2_namespace.demo_namespace.id
  ...
}
```
Here is a sanitized log from my environment with the important parts:
```
...
# module.rancher_management.module.rancher_storage.data.rancher2_cluster.cluster will be read during apply
# (config refers to values not yet known)
<= data "rancher2_cluster" "cluster"  {
  ...
    ~ id                                      = "local" -> (known after apply)
  ...
  }

# module.rancher_management.module.rancher_storage.rancher2_app.csi must be replaced
-/+ resource "rancher2_app" "csi" {
  ...
    ~ project_id       = "local:p-lzdnw" -> (known after apply) # forces replacement
  ...
  }

# module.rancher_management.module.rancher_storage.rancher2_project.storage must be replaced
-/+ resource "rancher2_project" "storage" {
  ...
    ~ cluster_id                = "local" -> (known after apply) # forces replacement
    ~ id                        = "local:p-lzdnw" -> (known after apply)
  ...
  }
...
```

**Comment by rawmind0** [comment]
This issue seems related to this tf module design and the terraform [datasource behaviour](https://www.terraform.io/docs/configuration/data-sources.html#data-resource-behavior). Terraform advices that datasources are updated on refresh stage (before apply) unless using "known after apply" values on them. 

Your tf plan is saying `module.rancher_management.module.rancher_storage.data.rancher2_cluster.cluster will be read during apply (config refers to values not yet known)`, so it will trigger the rest of the resources changes due to they depend on `known after apply` value. The `terraform apply` is not idempotent due to how datasource is defined within the tf module. 

Take a look to https://github.com/rancher/terraform-provider-rancher2/issues/460#issuecomment-694150705

**Comment by ba-work** [comment]
Right, but this continues to happen after every apply, regardless of if the value returned is different. For now I've worked around the issue by changing my module to accept the id as an input and the calling module that makes the cluster passes it from a cluster_sync resource. 

I think this an issue because other providers using this technique don't have this behavior. For instance, I make openstack instances based on keypair data source yet the instances are not modified every time I run the apply:
```tf
data "openstack_compute_keypair_v2" "keypair" {
  name = var.username
}
resource "openstack_compute_instance_v2" "instance" {
  ...
  key_pair = data.openstack_compute_keypair_v2.keypair.name
  ...
}
```
And the docs explicitly say: [key_pair - (Optional) The name of a key pair to put on the server. The key pair must already be created and associated with the tenant's account. Changing this creates a new server.](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_instance_v2#key_pair)

**Comment by rawmind0** [comment]
> Right, but this continues to happen after every apply, regardless of if the value returned is different. For now I've worked around the issue by changing my module to accept the id as an input and the calling module that makes the cluster passes it from a cluster_sync resource.

As mentioned, this is by design the defined and the expected behaviour for terraform datasources, out of the provider scope. If the datasource contains some argument `known after apply`, the datasource is unable to be refreshed before apply, triggering  updates on all resources that have some dependencies on it.

> I think this an issue because other providers using this technique don't have this behavior. For instance, I make openstack instances based on keypair data source yet the instances are not modified every time I run the apply:

This doesn't seem a provider issue. The distinct behaviour you mentioned, is caused by the dependant resource argument properties. If the affected argument has the property `ForceNew: true`, tf forces the recreation on the resource. That's why in this case, `rancher2_project` ([cluster_id](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_project.go#L102) argument has ForceNew property set) and `rancher2_app` ([project_id](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_app.go#L23) argument has ForceNew property set) are forced to be replaced, but not `rancher2_namespace` as not ForceNew argument updated.

Just setting a known value to `rancher2_cluster` datasource name argument, should make that `terraform apply` doesn't generate any diff. Something like that is not generating diff:
```
data "rancher2_cluster" "demo_cluster" { 
  name = "local"
}
resource "rancher2_project" "demo_project" {
  name       = "demo-project"
  cluster_id = data.rancher2_cluster.demo_cluster.id
}
resource "rancher2_namespace" "demo_namespace" {
  name       = "demo-ns"
  project_id = rancher2_project.demo_project.id
}
```
