### ISSUE TITLE
Support setting built-in rancher2_global_role to new_user_default

### ISSUE THREAD

**Issue by fpants** [rancher/terraform-provider-rancher2#629]
Chaning the built-in global role _user-base_ to be the new user default is only possible by importing it into the terraform state, and then be changing the new_user_default flag afterwards, but this is a multi-step process.
Would there be a way to define the role initially in terraform?

The process _as is_:

- Define rancher2_global_role initally:
`resource "rancher2_global_role" "user-base" {}`
- Import the resource into terraform state:
`> terraform import rancher2_global_role.user-base user-base`
- Define resource and change new_user_default flag:

```
resource "rancher2_global_role" "user-base" {
    name             = "User Base"
    new_user_default = true
}
```

**Comment by rawmind0** [comment]
All objects managed by terraform should be created by terraform or imported to it before can be managed. This is the current expected behaviour due to the object info should be included into tfstate. As alternative, you could define and create a new [global role](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/global_role) and set it as `new_user_default`

Also, i'd like to advice that `new_user_default` argument is cumulative, so setting it as true on a global role don't reset the argument if it's set on another global roles. I mean, if `user` global role has `new_user_default=true` and you also set it at `user-base` global role, new users will get both global role bindings by default.
