### ISSUE TITLE
hetzner_config doesn't allow labels

### ISSUE THREAD

**Issue by jmatsushita** [rancher/terraform-provider-rancher2#657]
`labels`  [as found in the terraform hetzner provider](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/data-sources/server#labels) (not to be confused with kubernetes node labels) are useful to for instance target a load balancer to a specific node pool.

Would it be possible to allow passing a `labels` map to the `hetzner_config` nested block?

**Comment by rawmind0** [comment]
@jmatsushita , i think that hetzner docker machine driver is not offering `labels` field, https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/master/driver.go#L23

**Comment by jmatsushita** [comment]
Thanks @rawmind0 Isn't the field named `serverLabels` ? https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/master/driver.go#L46

**Comment by rawmind0** [comment]
> Thanks @rawmind0 Isn't the field named serverLabels ? https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/master/driver.go#L46

@jmatsushita , may be that `serverLabels` would be the proper field but not sure. Anyway, this field is not set as "public" at golang struct, so json marshal/unmarshall is gonna ignore it. Same thing that https://github.com/rancher/terraform-provider-rancher2/issues/656#issuecomment-838730562

**Comment by stefandanaita** [comment]
Hi @rawmind0! The docker-machine-driver-hetzner library has a new version released (v3.6.0) which makes the ServerLabels public, along other things like placement groups. Any chance you would be able to update the `hetzner_config` object in the `rancher2_node_template` resource to allow setting the server_labels list and, maybe, the placement group id?

Thank you loads! At the moment creating a label selector load balancer on Hetzner with node pool targets is not really possible because of this. 🙏🏻

**Comment by rawmind0** [comment]
PR https://github.com/rancher/terraform-provider-rancher2/pull/851 is already merged. The fix will be available at next tfp release. Please reopen issue if required.
