### ISSUE TITLE
rancher2_project_logging doesn't show up on UI

### ISSUE THREAD

**Issue by martinhmuenster** [rancher/terraform-provider-rancher2#850]
rancher2 terraform provider, v1.21.0
Rancher running on Docker, v2.4.8
Terraform v0.13.7

Using the terraform configuration
```
resource "rancher2_project_logging" "kafka_example" {
  name = "Kafka"
  project_id = <project_id>
  kind = "kafka"
  kafka_config {
    topic = <kafka topic>
    broker_endpoints = <broker endpoints>
  }
}
```
, the apply is successful and Kafka logging is set up on my rancher instance (I can confirm that the brokers are receiving logs). However, on the Rancher project logging page (same project as configured in Terraform), **the UI does not show the updated logging configuration**.

I'm not sure if this issue exists for other types of logging besides Kafka, or whether it exists for cluster logging as well.

Expected result after successfully applying Kafka project logging:
![rancher_expected](https://user-images.githubusercontent.com/67657676/150415340-e38e580a-1bf9-4d93-80e2-bc5a4b8c6f32.jpg)

Actual result after successfully applying Kafka project logging:
![rancher_actual](https://user-images.githubusercontent.com/67657676/150415469-3ff24d64-c2e7-4d2d-a8f6-8e52f6cdb3e1.jpg)

**Comment by matttrach** [comment]
This issue was created 2 years ago, but this appears to be an issue with a resource that is no longer supported. The version of Terraform is very old, and the version of Rancher and the provider are old as well. As such, I am going to close this issue as stale, but feel free to open a new one if this is still a valid issue on newer versions of Rancher and the provider.
