### ISSUE TITLE
rancher2_certificate should support ECDSA Certificates

### ISSUE THREAD

**Issue by digi691** [rancher/terraform-provider-rancher2#863]
Looking at the source it seems structure_certificate.go only supports rsa.

https://github.com/rancher/terraform-provider-rancher2/blob/8a9c0e4022f659b823fb076a1cf0ae2325208fa3/rancher2/structure_certificate.go#L4

**Comment by digi691** [comment]
The Error when trying to use an ECDSA private key

```
Error: expanding certificate: expanding certificate: failed to decode PEM private key block

  on certificates.tf line 172, in resource "rancher2_certificate" "tls-certificates":
 172: resource "rancher2_certificate" "tls-certificates" {
```

**Comment by matttrach** [comment]
The last comment on this issue was 2 years ago, but it appears that the ECDSA cert that the provider is getting from Rancher is not PEM encoded. As such I am going to close this issue as stale, but if this is still an issue in newer versions of Rancher and the provider please feel free to open a new issue.
