### ISSUE TITLE
[FEATURE] rke2/k3s Rotate Certificates

### ISSUE THREAD

**Issue by jakefhyde** [rancher/terraform-provider-rancher2#869]
Implement certificate rotation according to https://github.com/rancher/rancher/issues/35343

**Comment by rancher-max** [comment]
Validated that using the terraform provider to provision a cluster, it is possible to rotate either individual certs or all certs. Multiple rotations on the same cluster are also successful. My steps in validating were:

1. Clone this repo, using master branch commit `b875ecde` to validate
2. I updated scripts/version.sh to pin the version to `9.99.9` for my testing but this is probably optional
3. Run `make build`. Since I'm on OSX, I also had to update line 9 in scripts/gobuild.sh to use a lowercase a: `declare -a OS_ARCH_ARG`
4. Ensure the resulting binary is able to be used as a provider. I followed some steps from https://www.infracloud.io/blogs/developing-terraform-custom-provider/#:~:text=Steps%20to%20copy%20provider%20executable%20to%20plugins%20directory. The key piece here is: `cp bin/terraform-provider-rancher2 ~/.terraform.d/plugins/registry.terraform.io/rancher/rancher2/9.99.9/darwin_amd64`
5. Build the terraform. See below for my files (shown as one big file here)
```
# Implicit Local Provider
terraform {
  required_providers {
    rancher2 = {
      source  = "rancher/rancher2"
      version = "9.99.9"
    }
  }
}

# Variables
variable "rancher_url" {
  type        = string
  description = "URL for Rancher."
}

variable "rancher_token_key" {
  type        = string
  description = "API bearer token for Rancher."
  sensitive   = true
}

# main.tf
provider "rancher2" {
  api_url   = var.rancher_url
  token_key = var.rancher_token_key
  insecure = true
}

# Create amazonec2 cloud credential
resource "rancher2_cloud_credential" "maxtf" {
  name = "maxtf"
  amazonec2_credential_config {
    access_key = "<aws key>"
    secret_key = "<aws secret>"
  }
}

# Create amazonec2 machine config v2
resource "rancher2_machine_config_v2" "maxtfec2config" {
  generate_name = "maxtfconfig"
  amazonec2_config {
    ami =  "<ami>"
    region = "<region>"
    subnet_id = "<subnet id>"
    vpc_id = "<vpc id>"
    zone = "a"
    security_group = ["<sg name>"]
  }
}

# Create a new rancher v2 amazonec2 RKE2 Cluster v2
resource "rancher2_cluster_v2" "maxrke2cluster" {
  name = "maxtfrke2"
  kubernetes_version = "v1.21.10+rke2r2"
  enable_network_policy = false
  default_cluster_role_for_project_members = "user"
  rke_config {
    machine_pools {
      name = "pool1"
      cloud_credential_secret_name = rancher2_cloud_credential.maxtf.id
      control_plane_role = true
      etcd_role = true
      worker_role = true
      quantity = 3
      machine_config {
        kind = rancher2_machine_config_v2.maxtfec2config.kind
        name = rancher2_machine_config_v2.maxtfec2config.name
      }
    }
  }
}
```
