### ISSUE TITLE
[FEATURE] rke2/k3s Etcd Snapshot Restore

### ISSUE THREAD

**Issue by jakefhyde** [rancher/terraform-provider-rancher2#872]
Implement etcd snapshot restore according to https://github.com/rancher/rancher/issues/34417

**Comment by a-blender** [comment]
Not blocked by S3 snapshot or UI testing. Will implement this feature.

**Comment by a-blender** [comment]
## Testing template

#### Root cause

Implement rke2/k3s etcd snapshot create and restore in terraform.
 
#### What was fixed, or what changes have occurred

Added the following functionality to rke2/k3s v2 provisioning

* etcd_snapshot_create (generation) - creates a snapshot of the cluster's etcd db
* etcd_snapshot_restore (name, generation, rke_restore_config) - restores the cluster to the snapshot specified in the name field
* Update terraform docs

So now, if you add etcd_snapshot_create or etcd_snapshot_restore to the rke_config field in a terraform config file, terraform will pass that RKE configuration to Rancher and it will be set on the cluster object spec. When Rancher checks for config updates, it will kick off/restore to a snapshot.

```
etcd_snapshot_create {
  generation = 2
}
```

```
etcd_snapshot_restore {
  name = "ablender-rke2-downstream-on-demand-ip-172-31-31-249.us-ea-dcf6b"
  generation = 1
}
```

#### Areas or cases that should be tested

Test steps

* Provision an rke2 3 node cluster in AWS EC2 via terraform on rainbow `2.6-head`
* Test `Snapshot Now` button to make sure that snapshots work. Use rke2 version `v1.22.9-rc4+rke2r1`. I did not see snapshots appear before this version.
* Add deployment/pod
* Add etcd snapshot create to terraform config, run terraform apply to create snapshot
* Remove deployment/pod
* Add etcd snapshot restore to terraform config, run terraform apply to restore to the previous snapshot. Verify that your data is restored.

Tf config

```
terraform {
  required_providers {
    rancher2 = {
      source = "rancher/rancher2"
      version = "1.23.0"
    }
  }
}

provider "rancher2" {
  api_url = "https://rainbow.cp-dev.rancher.space"
  token_key = "<Rancher API bearer token>"
  insecure = true
}

# Create amazonec2 machine config v2
resource "rancher2_machine_config_v2" "foo" {
  generate_name = "machine-config"
  amazonec2_config {
    ami =  "ami-020b9012dfce5d885"
    region = "us-east-2"
    security_group = []
    subnet_id = "subnet-b923bbc3"
    vpc_id = "vpc-fbd9e393"
    zone = "b"
  }
}

# Create a new rancher v2 amazonec2 RKE2 Cluster v2
resource "rancher2_cluster_v2" "ablender-rke2-downstream" {
  name = "ablender-rke2-downstream"
  kubernetes_version = "v1.22.9-rc4+rke2r1"
  enable_network_policy = false
  default_cluster_role_for_project_members = "user"
  rke_config {
    machine_pools {
      name = "pool1"
      cloud_credential_secret_name = "cattle-global-data:<AWS cloud credential token>"
      control_plane_role = true
      etcd_role = true
      worker_role = false
      quantity = 1
      machine_config {
        kind = rancher2_machine_config_v2.foo.kind
        name = rancher2_machine_config_v2.foo.name
      }
    }
    machine_pools {
      name = "pool2"
      cloud_credential_secret_name = "cattle-global-data:<AWS cloud credential token>"
      control_plane_role = false
      etcd_role = false
      worker_role = true
      drain_before_delete = true
      quantity = 1
      machine_config {
        kind = rancher2_machine_config_v2.foo.kind
        name = rancher2_machine_config_v2.foo.name
      }
    }
    etcd_snapshot_restore {
      name = "ablender-rke2-downstream-on-demand-ip-172-31-31-249.us-ea-dcf6b"
      generation = 1
    }
  }
}
```

#### What areas could experience regressions ?

Terraform snapshot create/restore could break if the snapshot fields or implementation changes in Rancher.
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head
Rancher cluster type: HA
Docker version: 20.10

Terraform version: v1.1.9
Source: terraform.example.com/local/rancher2
Version: 1.0.0

----------

### Testing: ###

Tested this feature with the following steps:
1. Provision an rke2 3 node cluster in AWS EC2 via terraform on 2.6-head
2. Add etcd snapshot create to terraform config, run terraform apply to create snapshot
3. Add deployment/pod
4. Upgrade k8s from 1.22 to 1.23
5. Add etcd snapshot restore to terraform config, run terraform apply to restore to the previous snapshot
Name for `etcd_snapshot_restore` is found under `managedFields` in the snapshot yaml and is **not** the file name for the etcd snapshot
![image.png](https://zube.io/files/rancher/0231234ffee370945dad8672c08bb241-image.png)
```
etcd_snapshot_restore {
    name = "name of snapshot"
    generation = 1
    restore_rke_config = "all/none/kubernetesVersion"
}
```
6. Verify that your data is restored.

The following scenarios were tested:
1. 1 etcd, 1 cp, 1 worker
  - restore_rke_config = "all"
  - restore_rke_config = "none"
  - restore_rke_config = "kubernetesVersion"
2. 1 etcd, 1 cp, 2 workers
  - restore_rke_config = "all"
  - restore_rke_config = "none"
  - restore_rke_config = "kubernetesVersion"
3. 3 etcd, 2 cp, 3 workers
  - restore_rke_config = "all"
  - restore_rke_config = "none"
  - restore_rke_config = "kubernetesVersion"

**Result** - Pass

All scenarios are Pass and snapshot and restore with terraform are working as expected
