### ISSUE TITLE
[FEATURE] rke2/k3s Drain Before Delete

### ISSUE THREAD

**Issue by jakefhyde** [rancher/terraform-provider-rancher2#873]
Implement rke2/k3s "Drain Before Delete" according to https://github.com/rancher/rancher/issues/35274

**Comment by a-blender** [comment]
## Testing template

#### Root cause

New feature: add `DrainBeforeDelete` support to custom RKE2/K3s clusters with Terraform.
 
#### What was fixed, or what changes have occurred

- Added drain_before_delete field to rke2/k3s [machine pool schema](https://github.com/rancher/terraform-provider-rancher2/blob/b875ecdefccfdf65f0603df177a77f739bc76f20/rancher2/schema_cluster_v2_rke_config_machine_pool.go#L44)
- Added drain_before_delete to the rke2/k3s [machine pool](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_cluster_v2_rke_config_machine_pool.go)
- Updated tests

#### Areas or cases that should be tested

1. Create an RKE2 cluster via Terraform

How to do step 1

- Clone https://github.com/rancher/terraform-provider-rancher2
- Compile a local terraform binary using this script

```
# When you run a `make bin` in the terraform-provider-rancher2 repo, it
# downloads a binary into your local cache from the specified source. To
# tell terraform to use a local binary, you need to overwrite the one in
# the cache.

# Add the following to your terraform config file. This tells terraform 
# to use the local cache https://terraform.io/cli/config/config-file.

: '
terraform {
  required_providers {
    rancher2 = {
      source = "terraform.example.com/local/rancher2"
      version = "1.0.0"
    }
  }
}
'

# Compile the local binary
make bin

# Remove lock file
rm -f .terraform.lock.hcl

# Overwrite the cached binary with your local one
cp terraform-provider-rancher2 ~/.terraform.d/plugins/terraform.example.com/local/rancher2/1.0.0/darwin_amd64/terraform-provider-rancher2
```

- Create a Terraform config to provision an RKE2 downstream cluster in EC2 with 2 nodes (1 cp/etcd with `drain_before_delete` not set, 1 worker with` drain_before_delete = true`)

```
terraform {
  required_providers {
    rancher2 = {
      source = "terraform.example.com/local/rancher2"
      version = "1.0.0"
    }
  }
}

provider "rancher2" {
  api_url    = "<url of local Rancher server>"
  token_key = "<Rancher API bearer token>"
  insecure = true
}

# Create amazonec2 machine config v2
resource "rancher2_machine_config_v2" "foo" {
  generate_name = "machine-config"
  amazonec2_config {
    ami =  "ami-020b9012dfce5d885"
    region = "us-east-2"
    security_group = []
    subnet_id = "subnet-b923bbc3"
    vpc_id = "vpc-fbd9e393"
    zone = "b"
  }
}

# Create a new rancher v2 amazonec2 RKE2 Cluster v2
resource "rancher2_cluster_v2" "ablender-rke2-downstream" {
  name = "ablender-rke2-downstream"
  kubernetes_version = "v1.21.4+rke2r1"
  enable_network_policy = false
  default_cluster_role_for_project_members = "user"
  rke_config {
    machine_pools {
      name = "pool1"
      cloud_credential_secret_name = "cattle-global-data:<AWS cloud credential>"
      control_plane_role = true
      etcd_role = true
      worker_role = false
      quantity = 1
      machine_config {
        kind = rancher2_machine_config_v2.foo.kind
        name = rancher2_machine_config_v2.foo.name
      }
    }
    machine_pools {
      name = "pool2"
      cloud_credential_secret_name = "cattle-global-data:<AWS cloud credential>"
      control_plane_role = false
      etcd_role = false
      worker_role = true
      drain_before_delete = true
      quantity = 1
      machine_config {
        kind = rancher2_machine_config_v2.foo.kind
        name = rancher2_machine_config_v2.foo.name
      }
    }
  }
}
```

- Run `terraform init`
- Run `terraform apply`

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/12955547/159084552-db9f5dc8-fba8-4e3a-b24e-03bda3a836e9.png">

2. View each MachineDeployment in the Rancher UI. The MachineDeployment for cp/etcd nodes should have the CAPI annotation `machine.cluster.x-k8s.io/exclude-node-draining` set in the deployment spec. The MachineDeployment for the worker nodes should _not_ have that annotation.

![image](https://user-images.githubusercontent.com/12955547/159085217-cb816a57-848f-4aa5-9cb9-314ff05ef0ab.png)

![image](https://user-images.githubusercontent.com/12955547/159085249-04da1c3c-e66b-4cbb-92ce-495da2e93aaa.png)

![image](https://user-images.githubusercontent.com/12955547/159085285-92744565-a15b-4ba0-9a7f-104292a2dc7b.png)

3. Create a K3s cluster with Terraform

How to do step 3

Do the exact same thing as above, but provision the EC2 nodes with K3s instead. Use this config file.

```
terraform {
  required_providers {
    rancher2 = {
      source = "terraform.example.com/local/rancher2"
      version = "1.0.0"
    }
  }
}

provider "rancher2" {
  api_url    = "<url of local Rancher server>"
  token_key = "<Rancher API bearer token>"
  insecure = true
}

# Create amazonec2 machine config v2
resource "rancher2_machine_config_v2" "foo" {
  generate_name = "machine-config"
  amazonec2_config {
    ami =  "ami-020b9012dfce5d885"
    region = "us-east-2"
    security_group = []
    subnet_id = "subnet-b923bbc3"
    vpc_id = "vpc-fbd9e393"
    zone = "b"
  }
}

# Create a new rancher v2 amazonec2 K3s Cluster v2
resource "rancher2_cluster_v2" "ablender-k3s-downstream" {
  name = "ablender-k3s-downstream"
  kubernetes_version = "v1.21.4+k3s1"
  enable_network_policy = false
  default_cluster_role_for_project_members = "user"
  rke_config {
    machine_pools {
      name = "pool1"
      cloud_credential_secret_name = "cattle-global-data:<AWS cloud credential>"
      control_plane_role = true
      etcd_role = true
      worker_role = false
      quantity = 1
      machine_config {
        kind = rancher2_machine_config_v2.foo.kind
        name = rancher2_machine_config_v2.foo.name
      }
    }
    machine_pools {
      name = "pool2"
      cloud_credential_secret_name = "cattle-global-data:<AWS cloud credential>"
      control_plane_role = false
      etcd_role = false
      worker_role = true
      drain_before_delete = true
      quantity = 1
      machine_config {
        kind = rancher2_machine_config_v2.foo.kind
        name = rancher2_machine_config_v2.foo.name
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/12955547/159084285-1dd4997f-3510-42b9-8e01-c910d5e85eab.png)

4. Repeat step 2 for K3s

![image](https://user-images.githubusercontent.com/12955547/159085353-eab3f180-7c57-417e-a95d-9bcd3f292a81.png)

![image](https://user-images.githubusercontent.com/12955547/159085369-ca2a3113-5d5b-4307-a74d-29396223d861.png)

![image](https://user-images.githubusercontent.com/12955547/159085386-5928d1e3-00ea-4e83-a7d5-aaf9c6229aaf.png)
 
#### What areas could experience regressions ?

RKE2/K3s node drain on deletion if the terraform schema is modified.
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b7c9b89
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2, k3s

----------

### Testing: ###

Tested this issue with the following steps provided by @Anna-Blendermann in the previous comment

**Result** - Pass

Deployments were successful for both rke2 and k3s with the correct configurations set. An issue was found and reopened, which can be tracked [here](https://github.com/rancher/terraform-provider-rancher2/issues/824)
